apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.5
          imagePullPolicy: IfNotPresent
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom: { secretKeyRef: { name: osss-secrets, key: KEYCLOAK_ADMIN } }
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom: { secretKeyRef: { name: osss-secrets, key: KEYCLOAK_ADMIN_PASSWORD } }
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL_HOST
              valueFrom: { configMapKeyRef: { name: osss-config, key: KEYCLOAK_DB_HOST } }
            - name: KC_DB_URL_PORT
              valueFrom: { configMapKeyRef: { name: osss-config, key: KEYCLOAK_DB_PORT } }
            - name: KC_DB_URL_DATABASE
              valueFrom: { configMapKeyRef: { name: osss-config, key: KEYCLOAK_DB } }
            - name: KC_DB_USERNAME
              valueFrom: { configMapKeyRef: { name: osss-config, key: KEYCLOAK_DB_USER } }
            - name: KC_DB_PASSWORD
              valueFrom: { secretKeyRef: { name: osss-secrets, key: KEYCLOAK_DB_PASSWORD } }
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/"
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 20
            periodSeconds: 20
