apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: osss

resources:
  - ../../namespace.yaml
  - ../../config/configmap.yaml
  - ../../secrets/secrets.placeholder.yaml
  - ../../postgres/statefulset.yaml
  - ../../postgres/service.yaml
  - ../../keycloak-postgres/statefulset.yaml
  - ../../keycloak-postgres/service.yaml
  - ../../redis/deployment.yaml
  - ../../redis/service.yaml
  - ../../api/deployment.yaml
  - ../../api/service.yaml
  - ../../web/deployment.yaml
  - ../../web/service.yaml
  - ../../keycloak/deployment.yaml
  - ../../keycloak/service.yaml

  # Enabled add-ons
  - ../../elasticsearch/statefulset.yaml
  - ../../elasticsearch/service.yaml
  - ../../kibana/deployment.yaml
  - ../../kibana/service.yaml
  - ../../consul/deployment.yaml
  - ../../consul/service.yaml


# Vault dev server
- ../../vault/deployment.yaml
- ../../vault/service.yaml
