from __future__ import annotations
import logging
from typing import Optional, Any, Dict, List

from OSSS.ai.agents.base_agent import BaseAgent
from OSSS.ai.context import AgentContext
from OSSS.ai.llm.llm_interface import LLMInterface
from OSSS.ai.utils.llm_text import coerce_llm_text


# Initialize logger
logger = logging.getLogger(__name__)


class AnswerSearchAgent(BaseAgent):
    def __init__(
        self,
        llm: LLMInterface,
        name: str = "answer_search",
        **kwargs: Any,
    ) -> None:
        # IMPORTANT: BaseAgent doesn't accept llm=
        super().__init__(name=name, **kwargs)
        self.llm = llm  # Store it on the instance
        logger.info(f"Initialized {self.__class__.__name__} with LLM interface: {llm.__class__.__name__}")

    async def run(self, context: AgentContext) -> AgentContext:
        logger.info(f"[{self.name}] Starting execution for context: {context.query}")

        query = (context.query or "").strip()

        if not query:
            logger.warning(f"[{self.name}] Received empty query, skipping execution.")
            context.add_agent_output(self.name, "No query provided")
            return context

        # Logging query being processed
        logger.debug(f"[{self.name}] Processing query: {query}")

        # For now: LLM-only "answer" (no real retrieval yet)
        messages = [
            {"role": "system", "content": "Answer the user's question clearly and concisely."},
            {"role": "user", "content": query},
        ]

        try:
            # Logging before LLM call
            logger.debug(f"[{self.name}] Sending message to LLM: {messages}")
            resp = await self.llm.ainvoke(messages)
            logger.debug(f"[{self.name}] Received response from LLM.")

            # Process LLM response
            answer_text = coerce_llm_text(resp).strip()
            logger.debug(f"[{self.name}] Answer generated by LLM: {answer_text}")

        except Exception as e:
            logger.error(f"[{self.name}] Failed to generate answer using LLM: {e}")
            context.add_agent_output(self.name, "Error generating answer")
            return context

        # Mock sources (this part will be filled with real retrieval in future)
        sources: List[Dict[str, Any]] = []  # TODO: fill when you add real retrieval
        logger.debug(f"[{self.name}] Sources: {sources}")

        payload = {
            "ok": True,
            "type": "answer_search",
            "answer_text": answer_text,
            "sources": sources,
        }

        # Log the payload being stored in the context
        logger.debug(f"[{self.name}] Storing answer_search_payload in execution state: {payload}")
        context.execution_state["answer_search_payload"] = payload

        # Log agent output
        logger.info(f"[{self.name}] Adding agent output: {answer_text}")
        context.add_agent_output(self.name, answer_text)

        # Log token usage
        input_tokens = getattr(resp, "input_tokens", 0) or 0
        output_tokens = getattr(resp, "output_tokens", 0) or 0
        total_tokens = getattr(resp, "tokens_used", 0) or 0

        logger.debug(f"[{self.name}] Token usage: input_tokens={input_tokens}, output_tokens={output_tokens}, total_tokens={total_tokens}")

        context.add_agent_token_usage(
            agent_name=self.name,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=total_tokens,
        )

        # Log the end of the agent's execution
        logger.info(f"[{self.name}] Execution completed successfully")

        return context
