# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AccommodationOut(APIModel):
    iep_plan_id: Any | None = None
    applies_to: str | None = None
    description: str
    created_at: datetime
    updated_at: datetime
    id: Any

class AccommodationCreate(APIModel):
    iep_plan_id: Any | None = None
    applies_to: str | None = None
    description: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AccommodationReplace(APIModel):
    iep_plan_id: Any | None = None
    applies_to: str | None = None
    description: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AccommodationPatch(APIModel):
    iep_plan_id: Any | None = None
    applies_to: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AccommodationList(APIModel):
    items: list[AccommodationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
