# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ActivityOut(APIModel):
    school_id: Any | None = None
    name: str
    description: str | None = None
    is_active: bool
    created_at: datetime
    updated_at: datetime
    id: Any

class ActivityCreate(APIModel):
    school_id: Any | None = None
    name: str
    description: str | None = None
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ActivityReplace(APIModel):
    school_id: Any | None = None
    name: str
    description: str | None = None
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ActivityPatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    description: str | None = None
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ActivityList(APIModel):
    items: list[ActivityOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
