# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AgendaItemFileOut(APIModel):
    agenda_item_id: Any
    file_id: Any
    caption: str | None = None

class AgendaItemFileCreate(APIModel):
    caption: str | None = None

class AgendaItemFileReplace(APIModel):
    caption: str | None = None

class AgendaItemFilePatch(APIModel):
    caption: str | None = None

class AgendaItemFileList(APIModel):
    items: list[AgendaItemFileOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
