# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AgendaItemOut(APIModel):
    meeting_id: Any
    parent_id: Any | None = None
    position: int
    title: str
    description: str | None = None
    linked_policy_id: Any | None = None
    linked_objective_id: Any | None = None
    time_allocated: int | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class AgendaItemCreate(APIModel):
    meeting_id: Any
    parent_id: Any | None = None
    position: int | None = None
    title: str
    description: str | None = None
    linked_policy_id: Any | None = None
    linked_objective_id: Any | None = None
    time_allocated: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaItemReplace(APIModel):
    meeting_id: Any
    parent_id: Any | None = None
    position: int | None = None
    title: str
    description: str | None = None
    linked_policy_id: Any | None = None
    linked_objective_id: Any | None = None
    time_allocated: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaItemPatch(APIModel):
    meeting_id: Any | None = None
    parent_id: Any | None = None
    position: int | None = None
    title: str | None = None
    description: str | None = None
    linked_policy_id: Any | None = None
    linked_objective_id: Any | None = None
    time_allocated: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaItemList(APIModel):
    items: list[AgendaItemOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
