# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import datetime
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AgendaItemOut(APIModel):
    meeting_id: uuid.UUID
    parent_id: uuid.UUID | None = None
    position: int
    title: str
    description: str | None = None
    linked_policy_id: uuid.UUID | None = None
    linked_objective_id: uuid.UUID | None = None
    time_allocated: int | None = Field(None, ge=0)
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class AgendaItemCreate(APIModel):
    meeting_id: uuid.UUID
    parent_id: uuid.UUID | None = None
    # DB default is 0; allow omit on create
    position: int | None = Field(None, ge=0)
    title: str = Field(..., max_length=255)
    description: str | None = None
    linked_policy_id: uuid.UUID | None = None
    linked_objective_id: uuid.UUID | None = None
    time_allocated: int | None = Field(None, ge=0)


class AgendaItemReplace(APIModel):
    meeting_id: uuid.UUID
    parent_id: uuid.UUID | None = None
    position: int | None = Field(None, ge=0)
    title: str = Field(..., max_length=255)
    description: str | None = None
    linked_policy_id: uuid.UUID | None = None
    linked_objective_id: uuid.UUID | None = None
    time_allocated: int | None = Field(None, ge=0)


class AgendaItemPatch(APIModel):
    meeting_id: uuid.UUID | None = None
    parent_id: uuid.UUID | None = None
    position: int | None = Field(None, ge=0)
    title: str | None = Field(None, max_length=255)
    description: str | None = None
    linked_policy_id: uuid.UUID | None = None
    linked_objective_id: uuid.UUID | None = None
    time_allocated: int | None = Field(None, ge=0)


class AgendaItemList(APIModel):
    items: list[AgendaItemOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
