# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AssetPartOut(APIModel):
    asset_id: Any
    part_id: Any
    qty: Decimal
    created_at: datetime
    updated_at: datetime

class AssetPartCreate(APIModel):
    qty: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssetPartReplace(APIModel):
    qty: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssetPartPatch(APIModel):
    qty: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssetPartList(APIModel):
    items: list[AssetPartOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
