# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AssignmentOut(APIModel):
    section_id: Any
    category_id: Any | None = None
    name: str
    due_date: date | None = None
    points_possible: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class AssignmentCreate(APIModel):
    section_id: Any
    category_id: Any | None = None
    name: str
    due_date: date | None = None
    points_possible: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssignmentReplace(APIModel):
    section_id: Any
    category_id: Any | None = None
    name: str
    due_date: date | None = None
    points_possible: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssignmentPatch(APIModel):
    section_id: Any | None = None
    category_id: Any | None = None
    name: str | None = None
    due_date: date | None = None
    points_possible: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssignmentList(APIModel):
    items: list[AssignmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
