# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AttendanceOut(APIModel):
    meeting_id: Any
    user_id: Any
    status: str | None = None
    arrived_at: datetime | None = None
    left_at: datetime | None = None

class AttendanceCreate(APIModel):
    status: str | None = None
    arrived_at: datetime | None = None
    left_at: datetime | None = None

class AttendanceReplace(APIModel):
    status: str | None = None
    arrived_at: datetime | None = None
    left_at: datetime | None = None

class AttendancePatch(APIModel):
    status: str | None = None
    arrived_at: datetime | None = None
    left_at: datetime | None = None

class AttendanceList(APIModel):
    items: list[AttendanceOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
