# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AttendanceEventOut(APIModel):
    student_id: Any
    section_meeting_id: Any | None = None
    date: date
    code: str
    minutes: int | None = None
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class AttendanceEventCreate(APIModel):
    student_id: Any
    section_meeting_id: Any | None = None
    date: date
    code: str
    minutes: int | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceEventReplace(APIModel):
    student_id: Any
    section_meeting_id: Any | None = None
    date: date
    code: str
    minutes: int | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceEventPatch(APIModel):
    student_id: Any | None = None
    section_meeting_id: Any | None = None
    date: date | None = None
    code: str | None = None
    minutes: int | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceEventList(APIModel):
    items: list[AttendanceEventOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
