# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AuditLogOut(APIModel):
    actor_id: Any | None = None
    action: str
    entity_type: str
    entity_id: Any
    metadata: Any | None = None
    occurred_at: datetime
    id: Any
    created_at: datetime
    updated_at: datetime

class AuditLogCreate(APIModel):
    actor_id: Any | None = None
    action: str
    entity_type: str
    entity_id: Any
    metadata: Any | None = None
    occurred_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AuditLogReplace(APIModel):
    actor_id: Any | None = None
    action: str
    entity_type: str
    entity_id: Any
    metadata: Any | None = None
    occurred_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AuditLogPatch(APIModel):
    actor_id: Any | None = None
    action: str | None = None
    entity_type: str | None = None
    entity_id: Any | None = None
    metadata: Any | None = None
    occurred_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AuditLogList(APIModel):
    items: list[AuditLogOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
