# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class BodyOut(APIModel):
    org_id: Any
    name: str
    type: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class BodyCreate(APIModel):
    org_id: Any
    name: str
    type: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BodyReplace(APIModel):
    org_id: Any
    name: str
    type: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BodyPatch(APIModel):
    org_id: Any | None = None
    name: str | None = None
    type: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BodyList(APIModel):
    items: list[BodyOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
