# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class BuildingOut(APIModel):
    facility_id: Any
    name: str
    code: str | None = None
    year_built: int | None = None
    floors_count: int | None = None
    gross_sqft: Decimal | None = None
    use_type: str | None = None
    address: Any | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class BuildingCreate(APIModel):
    facility_id: Any
    name: str
    code: str | None = None
    year_built: int | None = None
    floors_count: int | None = None
    gross_sqft: Decimal | None = None
    use_type: str | None = None
    address: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BuildingReplace(APIModel):
    facility_id: Any
    name: str
    code: str | None = None
    year_built: int | None = None
    floors_count: int | None = None
    gross_sqft: Decimal | None = None
    use_type: str | None = None
    address: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BuildingPatch(APIModel):
    facility_id: Any | None = None
    name: str | None = None
    code: str | None = None
    year_built: int | None = None
    floors_count: int | None = None
    gross_sqft: Decimal | None = None
    use_type: str | None = None
    address: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BuildingList(APIModel):
    items: list[BuildingOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
