# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class BusStopOut(APIModel):
    route_id: Any
    name: str
    latitude: Decimal | None = None
    longitude: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class BusStopCreate(APIModel):
    route_id: Any
    name: str
    latitude: Decimal | None = None
    longitude: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusStopReplace(APIModel):
    route_id: Any
    name: str
    latitude: Decimal | None = None
    longitude: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusStopPatch(APIModel):
    route_id: Any | None = None
    name: str | None = None
    latitude: Decimal | None = None
    longitude: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusStopList(APIModel):
    items: list[BusStopOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
