# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class BusStopTimeOut(APIModel):
    route_id: Any
    stop_id: Any
    arrival_time: Any
    departure_time: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class BusStopTimeCreate(APIModel):
    route_id: Any
    stop_id: Any
    arrival_time: Any
    departure_time: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusStopTimeReplace(APIModel):
    route_id: Any
    stop_id: Any
    arrival_time: Any
    departure_time: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusStopTimePatch(APIModel):
    route_id: Any | None = None
    stop_id: Any | None = None
    arrival_time: Any | None = None
    departure_time: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusStopTimeList(APIModel):
    items: list[BusStopTimeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
