# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ChannelOut(APIModel):
    org_id: Any
    name: str
    audience: str
    description: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class ChannelCreate(APIModel):
    org_id: Any
    name: str
    audience: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ChannelReplace(APIModel):
    org_id: Any
    name: str
    audience: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ChannelPatch(APIModel):
    org_id: Any | None = None
    name: str | None = None
    audience: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ChannelList(APIModel):
    items: list[ChannelOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
