# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICMotionOut(APIModel):
    agenda_item_id: Any
    text: str
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    result: str | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class CICMotionCreate(APIModel):
    agenda_item_id: Any
    text: str
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    result: str | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMotionReplace(APIModel):
    agenda_item_id: Any
    text: str
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    result: str | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMotionPatch(APIModel):
    agenda_item_id: Any | None = None
    text: str | None = None
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    result: str | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMotionList(APIModel):
    items: list[CICMotionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
