# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICResolutionOut(APIModel):
    meeting_id: Any
    title: str
    summary: str | None = None
    effective_date: date | None = None
    status: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class CICResolutionCreate(APIModel):
    meeting_id: Any
    title: str
    summary: str | None = None
    effective_date: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICResolutionReplace(APIModel):
    meeting_id: Any
    title: str
    summary: str | None = None
    effective_date: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICResolutionPatch(APIModel):
    meeting_id: Any | None = None
    title: str | None = None
    summary: str | None = None
    effective_date: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICResolutionList(APIModel):
    items: list[CICResolutionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
