# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICCommitteeOut(APIModel):
    organization_id: Any | None = None
    school_id: Any | None = None
    name: str
    description: str | None = None
    status: str
    created_at: datetime
    updated_at: datetime
    id: Any

class CICCommitteeCreate(APIModel):
    organization_id: Any | None = None
    school_id: Any | None = None
    name: str
    description: str | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICCommitteeReplace(APIModel):
    organization_id: Any | None = None
    school_id: Any | None = None
    name: str
    description: str | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICCommitteePatch(APIModel):
    organization_id: Any | None = None
    school_id: Any | None = None
    name: str | None = None
    description: str | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICCommitteeList(APIModel):
    items: list[CICCommitteeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
