# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICVoteOut(APIModel):
    motion_id: Any
    person_id: Any
    value: str
    created_at: datetime
    updated_at: datetime
    id: Any

class CICVoteCreate(APIModel):
    motion_id: Any
    person_id: Any
    value: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICVoteReplace(APIModel):
    motion_id: Any
    person_id: Any
    value: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICVotePatch(APIModel):
    motion_id: Any | None = None
    person_id: Any | None = None
    value: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICVoteList(APIModel):
    items: list[CICVoteOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
