# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICProposalOut(APIModel):
    committee_id: Any
    submitted_by_id: Any | None = None
    school_id: Any | None = None
    type: str
    subject_id: Any | None = None
    course_id: Any | None = None
    title: str
    rationale: str | None = None
    status: str
    submitted_at: datetime
    created_at: datetime
    updated_at: datetime
    id: Any

class CICProposalCreate(APIModel):
    committee_id: Any
    submitted_by_id: Any | None = None
    school_id: Any | None = None
    type: str
    subject_id: Any | None = None
    course_id: Any | None = None
    title: str
    rationale: str | None = None
    status: str | None = None
    submitted_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICProposalReplace(APIModel):
    committee_id: Any
    submitted_by_id: Any | None = None
    school_id: Any | None = None
    type: str
    subject_id: Any | None = None
    course_id: Any | None = None
    title: str
    rationale: str | None = None
    status: str | None = None
    submitted_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICProposalPatch(APIModel):
    committee_id: Any | None = None
    submitted_by_id: Any | None = None
    school_id: Any | None = None
    type: str | None = None
    subject_id: Any | None = None
    course_id: Any | None = None
    title: str | None = None
    rationale: str | None = None
    status: str | None = None
    submitted_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICProposalList(APIModel):
    items: list[CICProposalOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
