# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICMembershipOut(APIModel):
    committee_id: Any
    person_id: Any
    role: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    voting_member: bool
    created_at: datetime
    updated_at: datetime
    id: Any

class CICMembershipCreate(APIModel):
    committee_id: Any
    person_id: Any
    role: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    voting_member: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMembershipReplace(APIModel):
    committee_id: Any
    person_id: Any
    role: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    voting_member: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMembershipPatch(APIModel):
    committee_id: Any | None = None
    person_id: Any | None = None
    role: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    voting_member: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMembershipList(APIModel):
    items: list[CICMembershipOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
