# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICAgendaItemOut(APIModel):
    meeting_id: Any
    parent_id: Any | None = None
    position: int
    title: str
    description: str | None = None
    time_allocated_minutes: int | None = None
    subject_id: Any | None = None
    course_id: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class CICAgendaItemCreate(APIModel):
    meeting_id: Any
    parent_id: Any | None = None
    position: int | None = None
    title: str
    description: str | None = None
    time_allocated_minutes: int | None = None
    subject_id: Any | None = None
    course_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICAgendaItemReplace(APIModel):
    meeting_id: Any
    parent_id: Any | None = None
    position: int | None = None
    title: str
    description: str | None = None
    time_allocated_minutes: int | None = None
    subject_id: Any | None = None
    course_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICAgendaItemPatch(APIModel):
    meeting_id: Any | None = None
    parent_id: Any | None = None
    position: int | None = None
    title: str | None = None
    description: str | None = None
    time_allocated_minutes: int | None = None
    subject_id: Any | None = None
    course_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICAgendaItemList(APIModel):
    items: list[CICAgendaItemOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
