# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICMeetingOut(APIModel):
    committee_id: Any
    title: str
    scheduled_at: datetime
    ends_at: datetime | None = None
    location: str | None = None
    status: str
    is_public: bool
    created_at: datetime
    updated_at: datetime
    id: Any

class CICMeetingCreate(APIModel):
    committee_id: Any
    title: str
    scheduled_at: datetime
    ends_at: datetime | None = None
    location: str | None = None
    status: str | None = None
    is_public: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMeetingReplace(APIModel):
    committee_id: Any
    title: str
    scheduled_at: datetime
    ends_at: datetime | None = None
    location: str | None = None
    status: str | None = None
    is_public: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMeetingPatch(APIModel):
    committee_id: Any | None = None
    title: str | None = None
    scheduled_at: datetime | None = None
    ends_at: datetime | None = None
    location: str | None = None
    status: str | None = None
    is_public: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICMeetingList(APIModel):
    items: list[CICMeetingOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
