# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CICProposalDocumentOut(APIModel):
    proposal_id: Any
    document_id: Any | None = None
    file_uri: str | None = None
    label: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class CICProposalDocumentCreate(APIModel):
    proposal_id: Any
    document_id: Any | None = None
    file_uri: str | None = None
    label: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICProposalDocumentReplace(APIModel):
    proposal_id: Any
    document_id: Any | None = None
    file_uri: str | None = None
    label: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICProposalDocumentPatch(APIModel):
    proposal_id: Any | None = None
    document_id: Any | None = None
    file_uri: str | None = None
    label: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CICProposalDocumentList(APIModel):
    items: list[CICProposalDocumentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
