# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ClassRankOut(APIModel):
    school_id: Any
    term_id: Any
    student_id: Any
    rank: int
    created_at: datetime
    updated_at: datetime
    id: Any

class ClassRankCreate(APIModel):
    school_id: Any
    term_id: Any
    student_id: Any
    rank: int
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ClassRankReplace(APIModel):
    school_id: Any
    term_id: Any
    student_id: Any
    rank: int
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ClassRankPatch(APIModel):
    school_id: Any | None = None
    term_id: Any | None = None
    student_id: Any | None = None
    rank: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ClassRankList(APIModel):
    items: list[ClassRankOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
