# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CommSearchIndexOut(APIModel):
    entity_type: str
    entity_id: Any
    ts: Any | None = None

class CommSearchIndexCreate(APIModel):
    ts: Any | None = None

class CommSearchIndexReplace(APIModel):
    ts: Any | None = None

class CommSearchIndexPatch(APIModel):
    ts: Any | None = None

class CommSearchIndexList(APIModel):
    items: list[CommSearchIndexOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
