# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ConsequenceTypeOut(APIModel):
    code: str
    description: str | None = None
    created_at: datetime
    updated_at: datetime

class ConsequenceTypeCreate(APIModel):
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsequenceTypeReplace(APIModel):
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsequenceTypePatch(APIModel):
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsequenceTypeList(APIModel):
    items: list[ConsequenceTypeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
