# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ConsentOut(APIModel):
    person_id: Any
    consent_type: str
    granted: bool
    effective_date: date
    expires_on: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ConsentCreate(APIModel):
    person_id: Any
    consent_type: str
    granted: bool | None = None
    effective_date: date
    expires_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsentReplace(APIModel):
    person_id: Any
    consent_type: str
    granted: bool | None = None
    effective_date: date
    expires_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsentPatch(APIModel):
    person_id: Any | None = None
    consent_type: str | None = None
    granted: bool | None = None
    effective_date: date | None = None
    expires_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsentList(APIModel):
    items: list[ConsentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
