# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CourseSectionOut(APIModel):
    course_id: Any
    term_id: Any
    section_number: str
    capacity: int | None = None
    school_id: Any
    created_at: datetime
    updated_at: datetime
    id: Any

class CourseSectionCreate(APIModel):
    course_id: Any
    term_id: Any
    section_number: str
    capacity: int | None = None
    school_id: Any
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CourseSectionReplace(APIModel):
    course_id: Any
    term_id: Any
    section_number: str
    capacity: int | None = None
    school_id: Any
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CourseSectionPatch(APIModel):
    course_id: Any | None = None
    term_id: Any | None = None
    section_number: str | None = None
    capacity: int | None = None
    school_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CourseSectionList(APIModel):
    items: list[CourseSectionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
