# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CoursePrerequisiteOut(APIModel):
    course_id: Any
    prereq_course_id: Any
    created_at: datetime
    updated_at: datetime

class CoursePrerequisiteCreate(APIModel):
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CoursePrerequisiteReplace(APIModel):
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CoursePrerequisitePatch(APIModel):
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CoursePrerequisiteList(APIModel):
    items: list[CoursePrerequisiteOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
