# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DataQualityIssueOut(APIModel):
    entity_type: str
    entity_id: Any
    rule: str
    severity: str
    details: str | None = None
    detected_at: datetime
    created_at: datetime
    updated_at: datetime
    id: Any

class DataQualityIssueCreate(APIModel):
    entity_type: str
    entity_id: Any
    rule: str
    severity: str
    details: str | None = None
    detected_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DataQualityIssueReplace(APIModel):
    entity_type: str
    entity_id: Any
    rule: str
    severity: str
    details: str | None = None
    detected_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DataQualityIssuePatch(APIModel):
    entity_type: str | None = None
    entity_id: Any | None = None
    rule: str | None = None
    severity: str | None = None
    details: str | None = None
    detected_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DataQualityIssueList(APIModel):
    items: list[DataQualityIssueOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
