# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DepartmentOut(APIModel):
    school_id: Any
    name: str
    created_at: datetime
    updated_at: datetime
    id: Any

class DepartmentCreate(APIModel):
    school_id: Any
    name: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DepartmentReplace(APIModel):
    school_id: Any
    name: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DepartmentPatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DepartmentList(APIModel):
    items: list[DepartmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
