# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DocumentPermissionOut(APIModel):
    resource_type: str
    resource_id: Any
    principal_type: str
    principal_id: Any
    permission: str

class DocumentPermissionCreate(APIModel):

class DocumentPermissionReplace(APIModel):

class DocumentPermissionPatch(APIModel):

class DocumentPermissionList(APIModel):
    items: list[DocumentPermissionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
