# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DocumentNotificationOut(APIModel):
    document_id: Any
    user_id: Any
    subscribed: bool
    last_sent_at: datetime | None = None

class DocumentNotificationCreate(APIModel):
    subscribed: bool | None = None
    last_sent_at: datetime | None = None

class DocumentNotificationReplace(APIModel):
    subscribed: bool | None = None
    last_sent_at: datetime | None = None

class DocumentNotificationPatch(APIModel):
    subscribed: bool | None = None
    last_sent_at: datetime | None = None

class DocumentNotificationList(APIModel):
    items: list[DocumentNotificationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
