# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DocumentOut(APIModel):
    folder_id: uuid.UUID | None = None
    title: str
    current_version_id: uuid.UUID | None = None
    is_public: bool
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class DocumentCreate(APIModel):
    folder_id: uuid.UUID | None = None
    title: str = Field(..., max_length=255)
    current_version_id: uuid.UUID | None = None
    is_public: bool | None = None


class DocumentReplace(APIModel):
    folder_id: uuid.UUID | None = None
    title: str = Field(..., max_length=255)
    current_version_id: uuid.UUID | None = None
    is_public: bool | None = None


class DocumentPatch(APIModel):
    folder_id: uuid.UUID | None = None
    title: str | None = Field(None, max_length=255)
    current_version_id: uuid.UUID | None = None
    is_public: bool | None = None


class DocumentList(APIModel):
    items: list[DocumentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
