# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DocumentSearchIndexOut(APIModel):
    document_id: Any
    ts: Any | None = None

class DocumentSearchIndexCreate(APIModel):
    ts: Any | None = None

class DocumentSearchIndexReplace(APIModel):
    ts: Any | None = None

class DocumentSearchIndexPatch(APIModel):
    ts: Any | None = None

class DocumentSearchIndexList(APIModel):
    items: list[DocumentSearchIndexOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
