# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class EntityTagOut(APIModel):
    entity_type: str
    entity_id: Any
    tag_id: Any

class EntityTagCreate(APIModel):

class EntityTagReplace(APIModel):

class EntityTagPatch(APIModel):

class EntityTagList(APIModel):
    items: list[EntityTagOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
