# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class EventOut(APIModel):
    school_id: Any
    activity_id: Any | None = None
    title: str
    summary: str | None = None
    starts_at: datetime
    ends_at: datetime | None = None
    venue: str | None = None
    status: str
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class EventCreate(APIModel):
    school_id: Any
    activity_id: Any | None = None
    title: str
    summary: str | None = None
    starts_at: datetime
    ends_at: datetime | None = None
    venue: str | None = None
    status: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EventReplace(APIModel):
    school_id: Any
    activity_id: Any | None = None
    title: str
    summary: str | None = None
    starts_at: datetime
    ends_at: datetime | None = None
    venue: str | None = None
    status: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EventPatch(APIModel):
    school_id: Any | None = None
    activity_id: Any | None = None
    title: str | None = None
    summary: str | None = None
    starts_at: datetime | None = None
    ends_at: datetime | None = None
    venue: str | None = None
    status: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EventList(APIModel):
    items: list[EventOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
