# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ExportRunOut(APIModel):
    export_name: str
    ran_at: datetime
    status: str
    file_uri: str | None = None
    error: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ExportRunCreate(APIModel):
    export_name: str
    ran_at: datetime | None = None
    status: str | None = None
    file_uri: str | None = None
    error: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ExportRunReplace(APIModel):
    export_name: str
    ran_at: datetime | None = None
    status: str | None = None
    file_uri: str | None = None
    error: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ExportRunPatch(APIModel):
    export_name: str | None = None
    ran_at: datetime | None = None
    status: str | None = None
    file_uri: str | None = None
    error: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ExportRunList(APIModel):
    items: list[ExportRunOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
