# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FamilyPortalAccessOut(APIModel):
    guardian_id: Any
    student_id: Any
    permissions: str | None = None
    created_at: datetime
    updated_at: datetime

class FamilyPortalAccessCreate(APIModel):
    permissions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FamilyPortalAccessReplace(APIModel):
    permissions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FamilyPortalAccessPatch(APIModel):
    permissions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FamilyPortalAccessList(APIModel):
    items: list[FamilyPortalAccessOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
