# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FeatureFlagOut(APIModel):
    org_id: Any
    key: str
    enabled: bool

class FeatureFlagCreate(APIModel):
    enabled: bool | None = None

class FeatureFlagReplace(APIModel):
    enabled: bool | None = None

class FeatureFlagPatch(APIModel):
    enabled: bool | None = None

class FeatureFlagList(APIModel):
    items: list[FeatureFlagOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
