# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FileOut(APIModel):
    storage_key: str
    filename: str
    size: int | None = None
    mime_type: str | None = None
    created_by: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class FileCreate(APIModel):
    storage_key: str
    filename: str
    size: int | None = None
    mime_type: str | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FileReplace(APIModel):
    storage_key: str
    filename: str
    size: int | None = None
    mime_type: str | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FilePatch(APIModel):
    storage_key: str | None = None
    filename: str | None = None
    size: int | None = None
    mime_type: str | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FileList(APIModel):
    items: list[FileOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
