# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FiscalYearOut(APIModel):
    year: int
    start_date: date
    end_date: date
    is_closed: bool
    id: Any
    created_at: datetime
    updated_at: datetime

class FiscalYearCreate(APIModel):
    year: int
    start_date: date
    end_date: date
    is_closed: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FiscalYearReplace(APIModel):
    year: int
    start_date: date
    end_date: date
    is_closed: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FiscalYearPatch(APIModel):
    year: int | None = None
    start_date: date | None = None
    end_date: date | None = None
    is_closed: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FiscalYearList(APIModel):
    items: list[FiscalYearOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
