# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GLAccountOut(APIModel):
    code: str
    name: str
    acct_type: str
    active: bool
    attributes: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class GLAccountCreate(APIModel):
    code: str
    name: str
    acct_type: str
    active: bool | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLAccountReplace(APIModel):
    code: str
    name: str
    acct_type: str
    active: bool | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLAccountPatch(APIModel):
    code: str | None = None
    name: str | None = None
    acct_type: str | None = None
    active: bool | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLAccountList(APIModel):
    items: list[GLAccountOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
