# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GLSegmentValueOut(APIModel):
    segment_id: Any
    code: str
    name: str
    active: bool
    id: Any
    created_at: datetime
    updated_at: datetime

class GLSegmentValueCreate(APIModel):
    segment_id: Any
    code: str
    name: str
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLSegmentValueReplace(APIModel):
    segment_id: Any
    code: str
    name: str
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLSegmentValuePatch(APIModel):
    segment_id: Any | None = None
    code: str | None = None
    name: str | None = None
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLSegmentValueList(APIModel):
    items: list[GLSegmentValueOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
