# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GLSegmentOut(APIModel):
    code: str
    name: str
    seq: int
    length: int | None = None
    required: bool
    id: Any
    created_at: datetime
    updated_at: datetime

class GLSegmentCreate(APIModel):
    code: str
    name: str
    seq: int
    length: int | None = None
    required: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLSegmentReplace(APIModel):
    code: str
    name: str
    seq: int
    length: int | None = None
    required: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLSegmentPatch(APIModel):
    code: str | None = None
    name: str | None = None
    seq: int | None = None
    length: int | None = None
    required: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLSegmentList(APIModel):
    items: list[GLSegmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
