# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GoalOut(APIModel):
    plan_id: Any
    name: str
    description: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class GoalCreate(APIModel):
    plan_id: Any
    name: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GoalReplace(APIModel):
    plan_id: Any
    name: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GoalPatch(APIModel):
    plan_id: Any | None = None
    name: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GoalList(APIModel):
    items: list[GoalOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
