# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GpaCalculationOut(APIModel):
    student_id: Any
    term_id: Any
    gpa: Decimal
    created_at: datetime
    updated_at: datetime
    id: Any

class GpaCalculationCreate(APIModel):
    student_id: Any
    term_id: Any
    gpa: Decimal
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GpaCalculationReplace(APIModel):
    student_id: Any
    term_id: Any
    gpa: Decimal
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GpaCalculationPatch(APIModel):
    student_id: Any | None = None
    term_id: Any | None = None
    gpa: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GpaCalculationList(APIModel):
    items: list[GpaCalculationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
