# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GuardianOut(APIModel):
    relationship: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class GuardianCreate(APIModel):
    relationship: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GuardianReplace(APIModel):
    relationship: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GuardianPatch(APIModel):
    relationship: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GuardianList(APIModel):
    items: list[GuardianOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
