# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class HREmployeeOut(APIModel):
    person_id: Any | None = None
    employee_no: str
    primary_school_id: Any | None = None
    department_segment_id: Any | None = None
    employment_type: str | None = None
    status: str
    hire_date: date | None = None
    termination_date: date | None = None
    attributes: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class HREmployeeCreate(APIModel):
    person_id: Any | None = None
    employee_no: str
    primary_school_id: Any | None = None
    department_segment_id: Any | None = None
    employment_type: str | None = None
    status: str | None = None
    hire_date: date | None = None
    termination_date: date | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HREmployeeReplace(APIModel):
    person_id: Any | None = None
    employee_no: str
    primary_school_id: Any | None = None
    department_segment_id: Any | None = None
    employment_type: str | None = None
    status: str | None = None
    hire_date: date | None = None
    termination_date: date | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HREmployeePatch(APIModel):
    person_id: Any | None = None
    employee_no: str | None = None
    primary_school_id: Any | None = None
    department_segment_id: Any | None = None
    employment_type: str | None = None
    status: str | None = None
    hire_date: date | None = None
    termination_date: date | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HREmployeeList(APIModel):
    items: list[HREmployeeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
