# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class HRPositionOut(APIModel):
    title: str
    department_segment_id: Any | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class HRPositionCreate(APIModel):
    title: str
    department_segment_id: Any | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HRPositionReplace(APIModel):
    title: str
    department_segment_id: Any | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HRPositionPatch(APIModel):
    title: str | None = None
    department_segment_id: Any | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HRPositionList(APIModel):
    items: list[HRPositionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
