# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class HRPositionAssignmentOut(APIModel):
    employee_id: Any
    position_id: Any
    start_date: date
    end_date: date | None = None
    percent: Decimal | None = None
    funding_split: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class HRPositionAssignmentCreate(APIModel):
    employee_id: Any
    position_id: Any
    start_date: date
    end_date: date | None = None
    percent: Decimal | None = None
    funding_split: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HRPositionAssignmentReplace(APIModel):
    employee_id: Any
    position_id: Any
    start_date: date
    end_date: date | None = None
    percent: Decimal | None = None
    funding_split: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HRPositionAssignmentPatch(APIModel):
    employee_id: Any | None = None
    position_id: Any | None = None
    start_date: date | None = None
    end_date: date | None = None
    percent: Decimal | None = None
    funding_split: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HRPositionAssignmentList(APIModel):
    items: list[HRPositionAssignmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
