# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations

from typing import List
from datetime import datetime
from uuid import UUID
from decimal import Decimal

from pydantic import Field
from OSSS.schemas.base import APIModel


# --- Lightweight nested ref for read responses ---
class DepartmentRef(APIModel):
    """Minimal projection of a Department for HRPosition reads."""
    id: UUID
    name: str | None = Field(default=None, description="Department name (if loaded)")


class HRPositionOut(APIModel):
    title: str
    department_segment_id: UUID | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: dict | None = None

    id: UUID
    created_at: datetime
    updated_at: datetime

    # Expose related departments when preloaded (joinedload) or leave empty list
    departments: List[DepartmentRef] = Field(default_factory=list)


class HRPositionCreate(APIModel):
    title: str
    department_segment_id: UUID | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: dict | None = None

    # Optional: attach departments during creation (idempotent server-side)
    department_ids: List[UUID] = Field(default_factory=list, description="Departments to attach")

    # Server-managed; ignored if provided
    created_at: datetime | None = None
    updated_at: datetime | None = None


class HRPositionReplace(APIModel):
    """Full replacement (PUT semantics). Provide all fields."""
    title: str
    department_segment_id: UUID | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: dict | None = None

    # Set departments to exactly this list
    department_ids: List[UUID] = Field(default_factory=list)

    # Server-managed; ignored if provided
    created_at: datetime | None = None
    updated_at: datetime | None = None


class HRPositionPatch(APIModel):
    """Partial update (PATCH semantics). Supply only what changes."""
    title: str | None = None
    department_segment_id: UUID | None = None
    grade: str | None = None
    fte: Decimal | None = None
    attributes: dict | None = None

    # If provided, replace current set of departments
    department_ids: List[UUID] | None = Field(default=None)

    # Server-managed; ignored if provided
    created_at: datetime | None = None
    updated_at: datetime | None = None


class HRPositionList(APIModel):
    items: List[HRPositionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
