# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class IepPlanOut(APIModel):
    special_ed_case_id: Any
    effective_start: date
    effective_end: date | None = None
    summary: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class IepPlanCreate(APIModel):
    special_ed_case_id: Any
    effective_start: date
    effective_end: date | None = None
    summary: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IepPlanReplace(APIModel):
    special_ed_case_id: Any
    effective_start: date
    effective_end: date | None = None
    summary: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IepPlanPatch(APIModel):
    special_ed_case_id: Any | None = None
    effective_start: date | None = None
    effective_end: date | None = None
    summary: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IepPlanList(APIModel):
    items: list[IepPlanOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
