# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ImmunizationRecordOut(APIModel):
    student_id: Any
    immunization_id: Any
    date_administered: date
    dose_number: int | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ImmunizationRecordCreate(APIModel):
    student_id: Any
    immunization_id: Any
    date_administered: date
    dose_number: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ImmunizationRecordReplace(APIModel):
    student_id: Any
    immunization_id: Any
    date_administered: date
    dose_number: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ImmunizationRecordPatch(APIModel):
    student_id: Any | None = None
    immunization_id: Any | None = None
    date_administered: date | None = None
    dose_number: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ImmunizationRecordList(APIModel):
    items: list[ImmunizationRecordOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
