# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ImmunizationOut(APIModel):
    name: str
    code: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ImmunizationCreate(APIModel):
    name: str
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ImmunizationReplace(APIModel):
    name: str
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ImmunizationPatch(APIModel):
    name: str | None = None
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ImmunizationList(APIModel):
    items: list[ImmunizationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
