# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class JournalEntryLineOut(APIModel):
    entry_id: Any
    account_id: Any
    line_no: int
    description: str | None = None
    debit: Decimal
    credit: Decimal
    segment_overrides: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class JournalEntryLineCreate(APIModel):
    entry_id: Any
    account_id: Any
    line_no: int
    description: str | None = None
    debit: Decimal | None = None
    credit: Decimal | None = None
    segment_overrides: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalEntryLineReplace(APIModel):
    entry_id: Any
    account_id: Any
    line_no: int
    description: str | None = None
    debit: Decimal | None = None
    credit: Decimal | None = None
    segment_overrides: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalEntryLinePatch(APIModel):
    entry_id: Any | None = None
    account_id: Any | None = None
    line_no: int | None = None
    description: str | None = None
    debit: Decimal | None = None
    credit: Decimal | None = None
    segment_overrides: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalEntryLineList(APIModel):
    items: list[JournalEntryLineOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
