# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class JournalEntryOut(APIModel):
    batch_id: Any
    fiscal_period_id: Any
    je_no: str
    journal_date: date
    description: str | None = None
    status: str
    total_debits: Decimal
    total_credits: Decimal
    id: Any
    created_at: datetime
    updated_at: datetime

class JournalEntryCreate(APIModel):
    batch_id: Any
    fiscal_period_id: Any
    je_no: str
    journal_date: date
    description: str | None = None
    status: str | None = None
    total_debits: Decimal | None = None
    total_credits: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalEntryReplace(APIModel):
    batch_id: Any
    fiscal_period_id: Any
    je_no: str
    journal_date: date
    description: str | None = None
    status: str | None = None
    total_debits: Decimal | None = None
    total_credits: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalEntryPatch(APIModel):
    batch_id: Any | None = None
    fiscal_period_id: Any | None = None
    je_no: str | None = None
    journal_date: date | None = None
    description: str | None = None
    status: str | None = None
    total_debits: Decimal | None = None
    total_credits: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalEntryList(APIModel):
    items: list[JournalEntryOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
