# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class LeaseOut(APIModel):
    building_id: Any | None = None
    landlord: str | None = None
    tenant: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    base_rent: Decimal | None = None
    rent_schedule: Any | None = None
    options: Any | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class LeaseCreate(APIModel):
    building_id: Any | None = None
    landlord: str | None = None
    tenant: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    base_rent: Decimal | None = None
    rent_schedule: Any | None = None
    options: Any | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LeaseReplace(APIModel):
    building_id: Any | None = None
    landlord: str | None = None
    tenant: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    base_rent: Decimal | None = None
    rent_schedule: Any | None = None
    options: Any | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LeasePatch(APIModel):
    building_id: Any | None = None
    landlord: str | None = None
    tenant: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    base_rent: Decimal | None = None
    rent_schedule: Any | None = None
    options: Any | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LeaseList(APIModel):
    items: list[LeaseOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
