# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class LibraryItemOut(APIModel):
    school_id: Any
    title: str
    author: str | None = None
    isbn: str | None = None
    barcode: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class LibraryItemCreate(APIModel):
    school_id: Any
    title: str
    author: str | None = None
    isbn: str | None = None
    barcode: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryItemReplace(APIModel):
    school_id: Any
    title: str
    author: str | None = None
    isbn: str | None = None
    barcode: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryItemPatch(APIModel):
    school_id: Any | None = None
    title: str | None = None
    author: str | None = None
    isbn: str | None = None
    barcode: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryItemList(APIModel):
    items: list[LibraryItemOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
