# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class LibraryHoldOut(APIModel):
    item_id: Any
    person_id: Any
    placed_on: date
    expires_on: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class LibraryHoldCreate(APIModel):
    item_id: Any
    person_id: Any
    placed_on: date
    expires_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryHoldReplace(APIModel):
    item_id: Any
    person_id: Any
    placed_on: date
    expires_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryHoldPatch(APIModel):
    item_id: Any | None = None
    person_id: Any | None = None
    placed_on: date | None = None
    expires_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryHoldList(APIModel):
    items: list[LibraryHoldOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
