# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MeetingPermissionOut(APIModel):
    meeting_id: Any
    principal_type: str
    principal_id: Any
    permission: str

class MeetingPermissionCreate(APIModel):

class MeetingPermissionReplace(APIModel):

class MeetingPermissionPatch(APIModel):

class MeetingPermissionList(APIModel):
    items: list[MeetingPermissionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
