# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MeetingOut(APIModel):
    org_id: Any
    body_id: Any | None = None
    title: str
    starts_at: datetime
    ends_at: datetime | None = None
    location: str | None = None
    status: str | None = None
    is_public: bool
    stream_url: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class MeetingCreate(APIModel):
    org_id: Any
    body_id: Any | None = None
    title: str
    starts_at: datetime
    ends_at: datetime | None = None
    location: str | None = None
    status: str | None = None
    is_public: bool | None = None
    stream_url: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MeetingReplace(APIModel):
    org_id: Any
    body_id: Any | None = None
    title: str
    starts_at: datetime
    ends_at: datetime | None = None
    location: str | None = None
    status: str | None = None
    is_public: bool | None = None
    stream_url: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MeetingPatch(APIModel):
    org_id: Any | None = None
    body_id: Any | None = None
    title: str | None = None
    starts_at: datetime | None = None
    ends_at: datetime | None = None
    location: str | None = None
    status: str | None = None
    is_public: bool | None = None
    stream_url: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MeetingList(APIModel):
    items: list[MeetingOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
