# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MeetingFileOut(APIModel):
    meeting_id: Any
    file_id: Any
    caption: str | None = None

class MeetingFileCreate(APIModel):
    caption: str | None = None

class MeetingFileReplace(APIModel):
    caption: str | None = None

class MeetingFilePatch(APIModel):
    caption: str | None = None

class MeetingFileList(APIModel):
    items: list[MeetingFileOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
