# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MeetingSearchIndexOut(APIModel):
    meeting_id: Any
    ts: Any | None = None

class MeetingSearchIndexCreate(APIModel):
    ts: Any | None = None

class MeetingSearchIndexReplace(APIModel):
    ts: Any | None = None

class MeetingSearchIndexPatch(APIModel):
    ts: Any | None = None

class MeetingSearchIndexList(APIModel):
    items: list[MeetingSearchIndexOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
