# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MessageRecipientOut(APIModel):
    message_id: Any
    person_id: Any
    delivery_status: str | None = None
    delivered_at: datetime | None = None
    created_at: datetime
    updated_at: datetime

class MessageRecipientCreate(APIModel):
    delivery_status: str | None = None
    delivered_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MessageRecipientReplace(APIModel):
    delivery_status: str | None = None
    delivered_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MessageRecipientPatch(APIModel):
    delivery_status: str | None = None
    delivered_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MessageRecipientList(APIModel):
    items: list[MessageRecipientOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
