# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MessageOut(APIModel):
    sender_id: Any | None = None
    channel: str
    subject: str | None = None
    body: str | None = None
    sent_at: datetime | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class MessageCreate(APIModel):
    sender_id: Any | None = None
    channel: str
    subject: str | None = None
    body: str | None = None
    sent_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MessageReplace(APIModel):
    sender_id: Any | None = None
    channel: str
    subject: str | None = None
    body: str | None = None
    sent_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MessagePatch(APIModel):
    sender_id: Any | None = None
    channel: str | None = None
    subject: str | None = None
    body: str | None = None
    sent_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MessageList(APIModel):
    items: list[MessageOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
