# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MotionOut(APIModel):
    agenda_item_id: Any
    text: str
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    passed: bool | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class MotionCreate(APIModel):
    agenda_item_id: Any
    text: str
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    passed: bool | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MotionReplace(APIModel):
    agenda_item_id: Any
    text: str
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    passed: bool | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MotionPatch(APIModel):
    agenda_item_id: Any | None = None
    text: str | None = None
    moved_by_id: Any | None = None
    seconded_by_id: Any | None = None
    passed: bool | None = None
    tally_for: int | None = None
    tally_against: int | None = None
    tally_abstain: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MotionList(APIModel):
    items: list[MotionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
