# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class NotificationOut(APIModel):
    user_id: Any
    type: str
    payload: Any | None = None
    read_at: datetime | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class NotificationCreate(APIModel):
    user_id: Any
    type: str
    payload: Any | None = None
    read_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class NotificationReplace(APIModel):
    user_id: Any
    type: str
    payload: Any | None = None
    read_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class NotificationPatch(APIModel):
    user_id: Any | None = None
    type: str | None = None
    payload: Any | None = None
    read_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class NotificationList(APIModel):
    items: list[NotificationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
