# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel

# src/OSSS/db/models/order_create.py
# Do NOT declare a second mapped class here.
from .line_item import OrderLineItem  # reuse the mapping
__all__ = ["OrderLineItem"]


class OrderOut(APIModel):
    event_id: Any
    purchaser_user_id: Any | None = None
    total_cents: int
    currency: str
    status: str
    external_ref: str | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class OrderCreate(APIModel):
    event_id: Any
    purchaser_user_id: Any | None = None
    total_cents: int | None = None
    currency: str | None = None
    status: str | None = None
    external_ref: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class OrderReplace(APIModel):
    event_id: Any
    purchaser_user_id: Any | None = None
    total_cents: int | None = None
    currency: str | None = None
    status: str | None = None
    external_ref: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class OrderPatch(APIModel):
    event_id: Any | None = None
    purchaser_user_id: Any | None = None
    total_cents: int | None = None
    currency: str | None = None
    status: str | None = None
    external_ref: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class OrderList(APIModel):
    items: list[OrderOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
