# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class OrderLineItemOut(APIModel):
    order_id: Any
    ticket_type_id: Any
    quantity: int
    created_at: datetime
    updated_at: datetime
    id: Any

class OrderLineItemCreate(APIModel):
    order_id: Any
    ticket_type_id: Any
    quantity: int
    created_at: datetime | None = None
    updated_at: datetime | None = None

class OrderLineItemReplace(APIModel):
    order_id: Any
    ticket_type_id: Any
    quantity: int
    created_at: datetime | None = None
    updated_at: datetime | None = None

class OrderLineItemPatch(APIModel):
    order_id: Any | None = None
    ticket_type_id: Any | None = None
    quantity: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class OrderLineItemList(APIModel):
    items: list[OrderLineItemOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
