# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional
from datetime import datetime
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class OrganizationOut(APIModel):
    name: str
    code: str | None = None
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime
    # read-only relationship projections (IDs only)
    body_ids: list[uuid.UUID] | None = Field(
        default=None, description="IDs of related Body rows (read-only)"
    )
    curriculum_ids: list[uuid.UUID] | None = Field(
        default=None, description="IDs of related Curriculum rows (read-only)"
    )


class OrganizationCreate(APIModel):
    name: str
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


class OrganizationReplace(APIModel):
    name: str
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


class OrganizationPatch(APIModel):
    name: str | None = None
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


class OrganizationList(APIModel):
    items: list[OrganizationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
