# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PageOut(APIModel):
    channel_id: Any
    slug: str
    title: str
    body: str | None = None
    status: str
    published_at: datetime | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PageCreate(APIModel):
    channel_id: Any
    slug: str
    title: str
    body: str | None = None
    status: str | None = None
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PageReplace(APIModel):
    channel_id: Any
    slug: str
    title: str
    body: str | None = None
    status: str | None = None
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PagePatch(APIModel):
    channel_id: Any | None = None
    slug: str | None = None
    title: str | None = None
    body: str | None = None
    status: str | None = None
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PageList(APIModel):
    items: list[PageOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
