# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PartLocationOut(APIModel):
    part_id: Any
    building_id: Any | None = None
    space_id: Any | None = None
    location_code: str | None = None
    qty_on_hand: Decimal
    min_qty: Decimal | None = None
    max_qty: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PartLocationCreate(APIModel):
    part_id: Any
    building_id: Any | None = None
    space_id: Any | None = None
    location_code: str | None = None
    qty_on_hand: Decimal | None = None
    min_qty: Decimal | None = None
    max_qty: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PartLocationReplace(APIModel):
    part_id: Any
    building_id: Any | None = None
    space_id: Any | None = None
    location_code: str | None = None
    qty_on_hand: Decimal | None = None
    min_qty: Decimal | None = None
    max_qty: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PartLocationPatch(APIModel):
    part_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    location_code: str | None = None
    qty_on_hand: Decimal | None = None
    min_qty: Decimal | None = None
    max_qty: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PartLocationList(APIModel):
    items: list[PartLocationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
