# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PayPeriodOut(APIModel):
    code: str
    start_date: date
    end_date: date
    pay_date: date
    status: str
    id: Any
    created_at: datetime
    updated_at: datetime

class PayPeriodCreate(APIModel):
    code: str
    start_date: date
    end_date: date
    pay_date: date
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PayPeriodReplace(APIModel):
    code: str
    start_date: date
    end_date: date
    pay_date: date
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PayPeriodPatch(APIModel):
    code: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    pay_date: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PayPeriodList(APIModel):
    items: list[PayPeriodOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
