# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PaymentOut(APIModel):
    invoice_id: Any
    paid_on: date
    amount: Decimal
    method: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PaymentCreate(APIModel):
    invoice_id: Any
    paid_on: date
    amount: Decimal
    method: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PaymentReplace(APIModel):
    invoice_id: Any
    paid_on: date
    amount: Decimal
    method: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PaymentPatch(APIModel):
    invoice_id: Any | None = None
    paid_on: date | None = None
    amount: Decimal | None = None
    method: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PaymentList(APIModel):
    items: list[PaymentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
