# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PermissionOut(APIModel):
    code: str
    description: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PermissionCreate(APIModel):
    code: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PermissionReplace(APIModel):
    code: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PermissionPatch(APIModel):
    code: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PermissionList(APIModel):
    items: list[PermissionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
