# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PersonOut(APIModel):
    first_name: str
    last_name: str
    middle_name: str | None = None
    dob: date | None = None
    email: str | None = None
    phone: str | None = None
    gender: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PersonCreate(APIModel):
    first_name: str
    last_name: str
    middle_name: str | None = None
    dob: date | None = None
    email: str | None = None
    phone: str | None = None
    gender: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonReplace(APIModel):
    first_name: str
    last_name: str
    middle_name: str | None = None
    dob: date | None = None
    email: str | None = None
    phone: str | None = None
    gender: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonPatch(APIModel):
    first_name: str | None = None
    last_name: str | None = None
    middle_name: str | None = None
    dob: date | None = None
    email: str | None = None
    phone: str | None = None
    gender: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonList(APIModel):
    items: list[PersonOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
