# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PersonContactOut(APIModel):
    person_id: Any
    contact_id: Any
    label: str | None = None
    is_primary: bool
    is_emergency: bool
    created_at: datetime
    updated_at: datetime

class PersonContactCreate(APIModel):
    label: str | None = None
    is_primary: bool | None = None
    is_emergency: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonContactReplace(APIModel):
    label: str | None = None
    is_primary: bool | None = None
    is_emergency: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonContactPatch(APIModel):
    label: str | None = None
    is_primary: bool | None = None
    is_emergency: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonContactList(APIModel):
    items: list[PersonContactOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
