# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PersonalNoteOut(APIModel):
    user_id: Any
    entity_type: str
    entity_id: Any
    text: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PersonalNoteCreate(APIModel):
    user_id: Any
    entity_type: str
    entity_id: Any
    text: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonalNoteReplace(APIModel):
    user_id: Any
    entity_type: str
    entity_id: Any
    text: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonalNotePatch(APIModel):
    user_id: Any | None = None
    entity_type: str | None = None
    entity_id: Any | None = None
    text: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonalNoteList(APIModel):
    items: list[PersonalNoteOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
