# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PlanAssignmentOut(APIModel):
    entity_type: str
    entity_id: Any
    assignee_type: str
    assignee_id: Any

class PlanAssignmentCreate(APIModel):

class PlanAssignmentReplace(APIModel):

class PlanAssignmentPatch(APIModel):

class PlanAssignmentList(APIModel):
    items: list[PlanAssignmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
