# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PlanSearchIndexOut(APIModel):
    plan_id: Any
    ts: Any | None = None

class PlanSearchIndexCreate(APIModel):
    ts: Any | None = None

class PlanSearchIndexReplace(APIModel):
    ts: Any | None = None

class PlanSearchIndexPatch(APIModel):
    ts: Any | None = None

class PlanSearchIndexList(APIModel):
    items: list[PlanSearchIndexOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
