# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PMWorkGeneratorOut(APIModel):
    pm_plan_id: Any
    last_generated_at: datetime | None = None
    lookahead_days: int | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PMWorkGeneratorCreate(APIModel):
    pm_plan_id: Any
    last_generated_at: datetime | None = None
    lookahead_days: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PMWorkGeneratorReplace(APIModel):
    pm_plan_id: Any
    last_generated_at: datetime | None = None
    lookahead_days: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PMWorkGeneratorPatch(APIModel):
    pm_plan_id: Any | None = None
    last_generated_at: datetime | None = None
    lookahead_days: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PMWorkGeneratorList(APIModel):
    items: list[PMWorkGeneratorOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
