# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyOut(APIModel):
    org_id: Any
    code: str | None = None
    title: str
    status: str
    id: Any
    created_at: datetime
    updated_at: datetime

class PolicyCreate(APIModel):
    org_id: Any
    code: str | None = None
    title: str
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyReplace(APIModel):
    org_id: Any
    code: str | None = None
    title: str
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyPatch(APIModel):
    org_id: Any | None = None
    code: str | None = None
    title: str | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyList(APIModel):
    items: list[PolicyOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
