# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicySearchIndexOut(APIModel):
    policy_id: Any
    ts: Any | None = None

class PolicySearchIndexCreate(APIModel):
    ts: Any | None = None

class PolicySearchIndexReplace(APIModel):
    ts: Any | None = None

class PolicySearchIndexPatch(APIModel):
    ts: Any | None = None

class PolicySearchIndexList(APIModel):
    items: list[PolicySearchIndexOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
