# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyPublicationOut(APIModel):
    policy_version_id: Any
    published_at: datetime
    public_url: str | None = None
    is_current: bool

class PolicyPublicationCreate(APIModel):
    published_at: datetime | None = None
    public_url: str | None = None
    is_current: bool | None = None

class PolicyPublicationReplace(APIModel):
    published_at: datetime | None = None
    public_url: str | None = None
    is_current: bool | None = None

class PolicyPublicationPatch(APIModel):
    published_at: datetime | None = None
    public_url: str | None = None
    is_current: bool | None = None

class PolicyPublicationList(APIModel):
    items: list[PolicyPublicationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
