# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyFileOut(APIModel):
    policy_version_id: Any
    file_id: Any

class PolicyFileCreate(APIModel):

class PolicyFileReplace(APIModel):

class PolicyFilePatch(APIModel):

class PolicyFileList(APIModel):
    items: list[PolicyFileOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
