# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyVersionOut(APIModel):
    policy_id: Any
    version_no: int
    content: str | None = None
    effective_date: date | None = None
    supersedes_version_id: Any | None = None
    created_by: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PolicyVersionCreate(APIModel):
    policy_id: Any
    version_no: int | None = None
    content: str | None = None
    effective_date: date | None = None
    supersedes_version_id: Any | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyVersionReplace(APIModel):
    policy_id: Any
    version_no: int | None = None
    content: str | None = None
    effective_date: date | None = None
    supersedes_version_id: Any | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyVersionPatch(APIModel):
    policy_id: Any | None = None
    version_no: int | None = None
    content: str | None = None
    effective_date: date | None = None
    supersedes_version_id: Any | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyVersionList(APIModel):
    items: list[PolicyVersionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
