# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PostAttachmentOut(APIModel):
    post_id: Any
    file_id: Any

class PostAttachmentCreate(APIModel):

class PostAttachmentReplace(APIModel):

class PostAttachmentPatch(APIModel):

class PostAttachmentList(APIModel):
    items: list[PostAttachmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
