# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PostOut(APIModel):
    channel_id: Any
    title: str
    body: str | None = None
    status: str
    publish_at: datetime | None = None
    author_id: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PostCreate(APIModel):
    channel_id: Any
    title: str
    body: str | None = None
    status: str | None = None
    publish_at: datetime | None = None
    author_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PostReplace(APIModel):
    channel_id: Any
    title: str
    body: str | None = None
    status: str | None = None
    publish_at: datetime | None = None
    author_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PostPatch(APIModel):
    channel_id: Any | None = None
    title: str | None = None
    body: str | None = None
    status: str | None = None
    publish_at: datetime | None = None
    author_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PostList(APIModel):
    items: list[PostOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
