# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ProjectTaskOut(APIModel):
    project_id: Any
    name: str
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    percent_complete: Decimal | None = None
    assignee_user_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ProjectTaskCreate(APIModel):
    project_id: Any
    name: str
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    percent_complete: Decimal | None = None
    assignee_user_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProjectTaskReplace(APIModel):
    project_id: Any
    name: str
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    percent_complete: Decimal | None = None
    assignee_user_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProjectTaskPatch(APIModel):
    project_id: Any | None = None
    name: str | None = None
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    percent_complete: Decimal | None = None
    assignee_user_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProjectTaskList(APIModel):
    items: list[ProjectTaskOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
