# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ProjectOut(APIModel):
    school_id: Any | None = None
    name: str
    project_type: str | None = None
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    budget: Decimal | None = None
    description: str | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ProjectCreate(APIModel):
    school_id: Any | None = None
    name: str
    project_type: str | None = None
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    budget: Decimal | None = None
    description: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProjectReplace(APIModel):
    school_id: Any | None = None
    name: str
    project_type: str | None = None
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    budget: Decimal | None = None
    description: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProjectPatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    project_type: str | None = None
    status: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    budget: Decimal | None = None
    description: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProjectList(APIModel):
    items: list[ProjectOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
