# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import datetime
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ProposalDocumentOut(APIModel):
    proposal_id: uuid.UUID
    document_id: uuid.UUID | None = None
    file_uri: str | None = None
    label: str | None = None
    created_at: datetime
    updated_at: datetime
    id: uuid.UUID


class ProposalDocumentCreate(APIModel):
    proposal_id: uuid.UUID
    document_id: uuid.UUID | None = None
    file_uri: str | None = None
    label: str | None = None


class ProposalDocumentReplace(APIModel):
    proposal_id: uuid.UUID
    document_id: uuid.UUID | None = None
    file_uri: str | None = None
    label: str | None = None


class ProposalDocumentPatch(APIModel):
    proposal_id: uuid.UUID | None = None
    document_id: uuid.UUID | None = None
    file_uri: str | None = None
    label: str | None = None


class ProposalDocumentList(APIModel):
    items: list[ProposalDocumentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
