# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ProposalReviewOut(APIModel):
    proposal_id: Any
    reviewer_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ProposalReviewCreate(APIModel):
    proposal_id: Any
    reviewer_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProposalReviewReplace(APIModel):
    proposal_id: Any
    reviewer_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProposalReviewPatch(APIModel):
    proposal_id: Any | None = None
    reviewer_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ProposalReviewList(APIModel):
    items: list[ProposalReviewOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
