# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PublicationOut(APIModel):
    meeting_id: Any
    published_at: datetime
    public_url: str | None = None
    is_final: bool
    created_at: datetime
    updated_at: datetime
    id: Any

class PublicationCreate(APIModel):
    meeting_id: Any
    published_at: datetime | None = None
    public_url: str | None = None
    is_final: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PublicationReplace(APIModel):
    meeting_id: Any
    published_at: datetime | None = None
    public_url: str | None = None
    is_final: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PublicationPatch(APIModel):
    meeting_id: Any | None = None
    published_at: datetime | None = None
    public_url: str | None = None
    is_final: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PublicationList(APIModel):
    items: list[PublicationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
