# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ReportCardOut(APIModel):
    student_id: Any
    term_id: Any
    published_at: datetime | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ReportCardCreate(APIModel):
    student_id: Any
    term_id: Any
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ReportCardReplace(APIModel):
    student_id: Any
    term_id: Any
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ReportCardPatch(APIModel):
    student_id: Any | None = None
    term_id: Any | None = None
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ReportCardList(APIModel):
    items: list[ReportCardOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
