# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class RolePermissionOut(APIModel):
    role_id: Any
    permission_id: Any
    created_at: datetime
    updated_at: datetime

class RolePermissionCreate(APIModel):
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RolePermissionReplace(APIModel):
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RolePermissionPatch(APIModel):
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RolePermissionList(APIModel):
    items: list[RolePermissionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
