# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class RoleOut(APIModel):
    name: str
    description: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class RoleCreate(APIModel):
    name: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RoleReplace(APIModel):
    name: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RolePatch(APIModel):
    name: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RoleList(APIModel):
    items: list[RoleOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
