# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class RoomOut(APIModel):
    school_id: Any
    name: str
    capacity: int | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class RoomCreate(APIModel):
    school_id: Any
    name: str
    capacity: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RoomReplace(APIModel):
    school_id: Any
    name: str
    capacity: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RoomPatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    capacity: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class RoomList(APIModel):
    items: list[RoomOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
