# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ScanRequestOut(APIModel):
    qr_code: str
    location: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ScanRequestCreate(APIModel):
    qr_code: str
    location: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ScanRequestReplace(APIModel):
    qr_code: str
    location: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ScanRequestPatch(APIModel):
    qr_code: str | None = None
    location: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ScanRequestList(APIModel):
    items: list[ScanRequestOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
