# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SchoolOut(APIModel):
    organization_id: Any
    name: str
    school_code: str | None = None
    nces_school_id: str | None = None
    building_code: str | None = None
    type: str | None = None
    timezone: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SchoolCreate(APIModel):
    organization_id: Any
    name: str
    school_code: str | None = None
    nces_school_id: str | None = None
    building_code: str | None = None
    type: str | None = None
    timezone: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SchoolReplace(APIModel):
    organization_id: Any
    name: str
    school_code: str | None = None
    nces_school_id: str | None = None
    building_code: str | None = None
    type: str | None = None
    timezone: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SchoolPatch(APIModel):
    organization_id: Any | None = None
    name: str | None = None
    school_code: str | None = None
    nces_school_id: str | None = None
    building_code: str | None = None
    type: str | None = None
    timezone: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SchoolList(APIModel):
    items: list[SchoolOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
