# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ScorecardOut(APIModel):
    plan_id: Any
    name: str
    id: Any
    created_at: datetime
    updated_at: datetime

class ScorecardCreate(APIModel):
    plan_id: Any
    name: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ScorecardReplace(APIModel):
    plan_id: Any
    name: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ScorecardPatch(APIModel):
    plan_id: Any | None = None
    name: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ScorecardList(APIModel):
    items: list[ScorecardOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
