# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ScorecardKPIOut(APIModel):
    scorecard_id: Any
    kpi_id: Any
    display_order: int | None = None

class ScorecardKPICreate(APIModel):
    display_order: int | None = None

class ScorecardKPIReplace(APIModel):
    display_order: int | None = None

class ScorecardKPIPatch(APIModel):
    display_order: int | None = None

class ScorecardKPIList(APIModel):
    items: list[ScorecardKPIOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
