# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SectionRoomAssignmentOut(APIModel):
    section_id: Any
    room_id: Any
    start_date: date | None = None
    end_date: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SectionRoomAssignmentCreate(APIModel):
    section_id: Any
    room_id: Any
    start_date: date | None = None
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SectionRoomAssignmentReplace(APIModel):
    section_id: Any
    room_id: Any
    start_date: date | None = None
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SectionRoomAssignmentPatch(APIModel):
    section_id: Any | None = None
    room_id: Any | None = None
    start_date: date | None = None
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SectionRoomAssignmentList(APIModel):
    items: list[SectionRoomAssignmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
