# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SectionMeetingOut(APIModel):
    section_id: Any
    day_of_week: int
    period_id: Any | None = None
    room_id: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SectionMeetingCreate(APIModel):
    section_id: Any
    day_of_week: int
    period_id: Any | None = None
    room_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SectionMeetingReplace(APIModel):
    section_id: Any
    day_of_week: int
    period_id: Any | None = None
    room_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SectionMeetingPatch(APIModel):
    section_id: Any | None = None
    day_of_week: int | None = None
    period_id: Any | None = None
    room_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SectionMeetingList(APIModel):
    items: list[SectionMeetingOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
