# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SpaceReservationOut(APIModel):
    space_id: Any
    booked_by_user_id: Any | None = None
    start_at: datetime
    end_at: datetime
    purpose: str | None = None
    status: str
    setup: Any | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SpaceReservationCreate(APIModel):
    space_id: Any
    booked_by_user_id: Any | None = None
    start_at: datetime
    end_at: datetime
    purpose: str | None = None
    status: str | None = None
    setup: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpaceReservationReplace(APIModel):
    space_id: Any
    booked_by_user_id: Any | None = None
    start_at: datetime
    end_at: datetime
    purpose: str | None = None
    status: str | None = None
    setup: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpaceReservationPatch(APIModel):
    space_id: Any | None = None
    booked_by_user_id: Any | None = None
    start_at: datetime | None = None
    end_at: datetime | None = None
    purpose: str | None = None
    status: str | None = None
    setup: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpaceReservationList(APIModel):
    items: list[SpaceReservationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
