# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SpecialEducationCaseOut(APIModel):
    student_id: Any
    eligibility: str | None = None
    case_opened: date | None = None
    case_closed: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SpecialEducationCaseCreate(APIModel):
    student_id: Any
    eligibility: str | None = None
    case_opened: date | None = None
    case_closed: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpecialEducationCaseReplace(APIModel):
    student_id: Any
    eligibility: str | None = None
    case_opened: date | None = None
    case_closed: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpecialEducationCasePatch(APIModel):
    student_id: Any | None = None
    eligibility: str | None = None
    case_opened: date | None = None
    case_closed: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpecialEducationCaseList(APIModel):
    items: list[SpecialEducationCaseOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
