# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Dict, Any
from datetime import datetime, date
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StandardOut(APIModel):
    code: str = Field(..., max_length=128)
    description: str
    parent_id: uuid.UUID | None = None
    grade_band: str | None = Field(None, max_length=64)
    effective_from: date | None = None
    effective_to: date | None = None
    attributes: Dict[str, Any] | None = None
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class StandardCreate(APIModel):
    code: str = Field(..., max_length=128)
    description: str
    parent_id: uuid.UUID | None = None
    grade_band: str | None = Field(None, max_length=64)
    effective_from: date | None = None
    effective_to: date | None = None
    attributes: Dict[str, Any] | None = None


class StandardReplace(StandardCreate):
    pass


class StandardPatch(APIModel):
    code: str | None = Field(None, max_length=128)
    description: str | None = None
    parent_id: uuid.UUID | None = None
    grade_band: str | None = Field(None, max_length=64)
    effective_from: date | None = None
    effective_to: date | None = None
    attributes: Dict[str, Any] | None = None


class StandardList(APIModel):
    items: list[StandardOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
