# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StateReportingSnapshotOut(APIModel):
    as_of_date: date
    scope: str | None = None
    payload: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class StateReportingSnapshotCreate(APIModel):
    as_of_date: date
    scope: str | None = None
    payload: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StateReportingSnapshotReplace(APIModel):
    as_of_date: date
    scope: str | None = None
    payload: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StateReportingSnapshotPatch(APIModel):
    as_of_date: date | None = None
    scope: str | None = None
    payload: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StateReportingSnapshotList(APIModel):
    items: list[StateReportingSnapshotOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
