# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StateOut(APIModel):
    code: str
    name: str

class StateCreate(APIModel):
    name: str

class StateReplace(APIModel):
    name: str

class StatePatch(APIModel):
    name: str | None = None

class StateList(APIModel):
    items: list[StateOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
