# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StudentProgramEnrollmentOut(APIModel):
    student_id: Any
    program_name: str
    start_date: date
    end_date: date | None = None
    status: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class StudentProgramEnrollmentCreate(APIModel):
    student_id: Any
    program_name: str
    start_date: date
    end_date: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentProgramEnrollmentReplace(APIModel):
    student_id: Any
    program_name: str
    start_date: date
    end_date: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentProgramEnrollmentPatch(APIModel):
    student_id: Any | None = None
    program_name: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentProgramEnrollmentList(APIModel):
    items: list[StudentProgramEnrollmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
