# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StudentOut(APIModel):
    student_number: str | None = None
    graduation_year: int | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class StudentCreate(APIModel):
    student_number: str | None = None
    graduation_year: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentReplace(APIModel):
    student_number: str | None = None
    graduation_year: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentPatch(APIModel):
    student_number: str | None = None
    graduation_year: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentList(APIModel):
    items: list[StudentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
