# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StudentGuardianOut(APIModel):
    student_id: Any
    guardian_id: Any
    custody: str | None = None
    is_primary: bool
    contact_order: int | None = None
    created_at: datetime
    updated_at: datetime

class StudentGuardianCreate(APIModel):
    custody: str | None = None
    is_primary: bool | None = None
    contact_order: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentGuardianReplace(APIModel):
    custody: str | None = None
    is_primary: bool | None = None
    contact_order: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentGuardianPatch(APIModel):
    custody: str | None = None
    is_primary: bool | None = None
    contact_order: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentGuardianList(APIModel):
    items: list[StudentGuardianOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
