# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SubjectOut(APIModel):
    department_id: Any | None = None
    name: str
    code: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SubjectCreate(APIModel):
    department_id: Any | None = None
    name: str
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SubjectReplace(APIModel):
    department_id: Any | None = None
    name: str
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SubjectPatch(APIModel):
    department_id: Any | None = None
    name: str | None = None
    code: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SubjectList(APIModel):
    items: list[SubjectOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
