# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SubscriptionOut(APIModel):
    channel_id: Any
    principal_type: str
    principal_id: Any
    created_at: datetime

class SubscriptionCreate(APIModel):
    created_at: datetime | None = None

class SubscriptionReplace(APIModel):
    created_at: datetime | None = None

class SubscriptionPatch(APIModel):
    created_at: datetime | None = None

class SubscriptionList(APIModel):
    items: list[SubscriptionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
