# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class TeacherSectionAssignmentOut(APIModel):
    staff_id: Any
    section_id: Any
    role: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class TeacherSectionAssignmentCreate(APIModel):
    staff_id: Any
    section_id: Any
    role: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TeacherSectionAssignmentReplace(APIModel):
    staff_id: Any
    section_id: Any
    role: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TeacherSectionAssignmentPatch(APIModel):
    staff_id: Any | None = None
    section_id: Any | None = None
    role: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TeacherSectionAssignmentList(APIModel):
    items: list[TeacherSectionAssignmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
