# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class TestAdministrationOut(APIModel):
    test_id: Any
    administration_date: date
    school_id: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class TestAdministrationCreate(APIModel):
    test_id: Any
    administration_date: date
    school_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TestAdministrationReplace(APIModel):
    test_id: Any
    administration_date: date
    school_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TestAdministrationPatch(APIModel):
    test_id: Any | None = None
    administration_date: date | None = None
    school_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TestAdministrationList(APIModel):
    items: list[TestAdministrationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
