# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class TicketTypeOut(APIModel):
    event_id: Any
    name: str
    price_cents: int
    quantity_total: int
    quantity_sold: int
    sales_starts_at: datetime | None = None
    sales_ends_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class TicketTypeCreate(APIModel):
    event_id: Any
    name: str
    price_cents: int | None = None
    quantity_total: int | None = None
    quantity_sold: int | None = None
    sales_starts_at: datetime | None = None
    sales_ends_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketTypeReplace(APIModel):
    event_id: Any
    name: str
    price_cents: int | None = None
    quantity_total: int | None = None
    quantity_sold: int | None = None
    sales_starts_at: datetime | None = None
    sales_ends_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketTypePatch(APIModel):
    event_id: Any | None = None
    name: str | None = None
    price_cents: int | None = None
    quantity_total: int | None = None
    quantity_sold: int | None = None
    sales_starts_at: datetime | None = None
    sales_ends_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketTypeList(APIModel):
    items: list[TicketTypeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
