# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class TicketScanOut(APIModel):
    ticket_id: Any
    scanned_by_user_id: Any | None = None
    scanned_at: datetime
    result: str
    location: str | None = None
    meta: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class TicketScanCreate(APIModel):
    ticket_id: Any
    scanned_by_user_id: Any | None = None
    scanned_at: datetime | None = None
    result: str
    location: str | None = None
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketScanReplace(APIModel):
    ticket_id: Any
    scanned_by_user_id: Any | None = None
    scanned_at: datetime | None = None
    result: str
    location: str | None = None
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketScanPatch(APIModel):
    ticket_id: Any | None = None
    scanned_by_user_id: Any | None = None
    scanned_at: datetime | None = None
    result: str | None = None
    location: str | None = None
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketScanList(APIModel):
    items: list[TicketScanOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
