# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class UserAccountOut(APIModel):
    person_id: Any
    username: str
    password_hash: str | None = None
    is_active: bool
    created_at: datetime
    updated_at: datetime
    id: Any

class UserAccountCreate(APIModel):
    person_id: Any
    username: str
    password_hash: str | None = None
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class UserAccountReplace(APIModel):
    person_id: Any
    username: str
    password_hash: str | None = None
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class UserAccountPatch(APIModel):
    person_id: Any | None = None
    username: str | None = None
    password_hash: str | None = None
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class UserAccountList(APIModel):
    items: list[UserAccountOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
