# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class WarrantyOut(APIModel):
    asset_id: Any
    vendor_id: Any | None = None
    policy_no: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    terms: str | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class WarrantyCreate(APIModel):
    asset_id: Any
    vendor_id: Any | None = None
    policy_no: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    terms: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WarrantyReplace(APIModel):
    asset_id: Any
    vendor_id: Any | None = None
    policy_no: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    terms: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WarrantyPatch(APIModel):
    asset_id: Any | None = None
    vendor_id: Any | None = None
    policy_no: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    terms: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WarrantyList(APIModel):
    items: list[WarrantyOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
