# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class WebhookOut(APIModel):
    target_url: str
    secret: str | None = None
    events: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class WebhookCreate(APIModel):
    target_url: str
    secret: str | None = None
    events: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WebhookReplace(APIModel):
    target_url: str
    secret: str | None = None
    events: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WebhookPatch(APIModel):
    target_url: str | None = None
    secret: str | None = None
    events: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WebhookList(APIModel):
    items: list[WebhookOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
