# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class WorkOrderTaskOut(APIModel):
    work_order_id: Any
    seq: int
    title: str
    is_mandatory: bool
    status: str | None = None
    completed_at: datetime | None = None
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class WorkOrderTaskCreate(APIModel):
    work_order_id: Any
    seq: int | None = None
    title: str
    is_mandatory: bool | None = None
    status: str | None = None
    completed_at: datetime | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderTaskReplace(APIModel):
    work_order_id: Any
    seq: int | None = None
    title: str
    is_mandatory: bool | None = None
    status: str | None = None
    completed_at: datetime | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderTaskPatch(APIModel):
    work_order_id: Any | None = None
    seq: int | None = None
    title: str | None = None
    is_mandatory: bool | None = None
    status: str | None = None
    completed_at: datetime | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderTaskList(APIModel):
    items: list[WorkOrderTaskOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
