# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class WorkOrderOut(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    request_id: Any | None = None
    status: str
    priority: str | None = None
    category: str | None = None
    summary: str
    description: str | None = None
    requested_due_at: datetime | None = None
    scheduled_start_at: datetime | None = None
    scheduled_end_at: datetime | None = None
    completed_at: datetime | None = None
    assigned_to_user_id: Any | None = None
    materials_cost: Decimal | None = None
    labor_cost: Decimal | None = None
    other_cost: Decimal | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class WorkOrderCreate(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    request_id: Any | None = None
    status: str | None = None
    priority: str | None = None
    category: str | None = None
    summary: str
    description: str | None = None
    requested_due_at: datetime | None = None
    scheduled_start_at: datetime | None = None
    scheduled_end_at: datetime | None = None
    completed_at: datetime | None = None
    assigned_to_user_id: Any | None = None
    materials_cost: Decimal | None = None
    labor_cost: Decimal | None = None
    other_cost: Decimal | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderReplace(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    request_id: Any | None = None
    status: str | None = None
    priority: str | None = None
    category: str | None = None
    summary: str
    description: str | None = None
    requested_due_at: datetime | None = None
    scheduled_start_at: datetime | None = None
    scheduled_end_at: datetime | None = None
    completed_at: datetime | None = None
    assigned_to_user_id: Any | None = None
    materials_cost: Decimal | None = None
    labor_cost: Decimal | None = None
    other_cost: Decimal | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderPatch(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    request_id: Any | None = None
    status: str | None = None
    priority: str | None = None
    category: str | None = None
    summary: str | None = None
    description: str | None = None
    requested_due_at: datetime | None = None
    scheduled_start_at: datetime | None = None
    scheduled_end_at: datetime | None = None
    completed_at: datetime | None = None
    assigned_to_user_id: Any | None = None
    materials_cost: Decimal | None = None
    labor_cost: Decimal | None = None
    other_cost: Decimal | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderList(APIModel):
    items: list[WorkOrderOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
