# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class WorkOrderPartOut(APIModel):
    work_order_id: Any
    part_id: Any | None = None
    qty: Decimal
    unit_cost: Decimal | None = None
    extended_cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class WorkOrderPartCreate(APIModel):
    work_order_id: Any
    part_id: Any | None = None
    qty: Decimal | None = None
    unit_cost: Decimal | None = None
    extended_cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderPartReplace(APIModel):
    work_order_id: Any
    part_id: Any | None = None
    qty: Decimal | None = None
    unit_cost: Decimal | None = None
    extended_cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderPartPatch(APIModel):
    work_order_id: Any | None = None
    part_id: Any | None = None
    qty: Decimal | None = None
    unit_cost: Decimal | None = None
    extended_cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderPartList(APIModel):
    items: list[WorkOrderPartOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
