
[alembic]
script_location = alembic

# your DB URL here
#sqlalchemy.url = postgresql+psycopg2://user:pass@db:5432/app

# Optionally make SQLAlchemy itself echo SQL (prints to stdout)
sqlalchemy.echo = true

[loggers]
keys = root, alembic, sqlalchemy, sqlalchemy_engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console

[logger_alembic]
level = DEBUG
handlers = console
qualname = alembic

# High level SQL logs (statements)
[logger_sqlalchemy_engine]
level = DEBUG
handlers = console
qualname = sqlalchemy.engine
propagate = 0

# If you also want bound parameters, bump to DEBUG:
#[logger_sqlalchemy_engine]
#level = DEBUG

[logger_sqlalchemy]
level = DEBUG
handlers = console
qualname = sqlalchemy
propagate = 1

[handler_console]
class = StreamHandler
level = NOTSET
args = (sys.stdout,)
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
