filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.container.id}/*-json.log
        processors:
          - add_docker_metadata: ~
          - decode_json_fields:
              fields: ["message"]
              target: ""
              overwrite_keys: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

# ✅ Runtime output via ES API key (id:api_key, NOT base64)
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS:http://elasticsearch:9200}"]
  api_key: "${ELASTIC_API_KEY}"

# 🚫 Don’t let the running beat hit Kibana
setup.dashboards.enabled: false
# (You can omit setup.kibana entirely for the runtime service)

