import logging
import asyncio

from OSSS.ai.config.logging_config import setup_logging
from OSSS.ai.agents.historian.agent import HistorianAgent
from OSSS.ai.context import AgentContext

setup_logging()
logger = logging.getLogger(__name__)


async def run_historian(query: str) -> str:
    """
    Run the HistorianAgent with the given query asynchronously.

    Parameters
    ----------
    query : str
        The input query string to be processed by the HistorianAgent.

    Returns
    -------
    str
        The output string generated by the HistorianAgent.
    """
    agent = HistorianAgent()
    context = AgentContext(query=query)
    logger.info(f"[{agent.name}] Running agent with query: {query}")
    await agent.run(context)
    output = context.get_output(agent.name)
    logger.info(f"[{agent.name}] Output: {output}")
    logger.debug(f"[{agent.name}] Trace: {context.agent_trace.get(agent.name, [])}")
    return output or "[No output]"


if __name__ == "__main__":  # pragma: no cover
    query = input("Enter a query: ").strip()
    output = asyncio.run(run_historian(query))
    print("\n🕵️ Historian Output:\n", output)