apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: serf-tcp
      port: 8301
      targetPort: 8301
    - name: serf-udp
      port: 8301
      targetPort: 8301
      protocol: UDP
    - name: server
      port: 8300
      targetPort: 8300
    - name: dns
      port: 8600
      targetPort: 8600
      protocol: UDP
