# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AcademicTermOut(APIModel):
    school_id: Any
    name: str
    type: str | None = None
    start_date: date
    end_date: date
    created_at: datetime
    updated_at: datetime
    id: Any

class AcademicTermCreate(APIModel):
    school_id: Any
    name: str
    type: str | None = None
    start_date: date
    end_date: date
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AcademicTermReplace(APIModel):
    school_id: Any
    name: str
    type: str | None = None
    start_date: date
    end_date: date
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AcademicTermPatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    type: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AcademicTermList(APIModel):
    items: list[AcademicTermOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
