# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AddressOut(APIModel):
    line1: str
    line2: str | None = None
    city: str
    state: str | None = None
    postal_code: str | None = None
    country: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class AddressCreate(APIModel):
    line1: str
    line2: str | None = None
    city: str
    state: str | None = None
    postal_code: str | None = None
    country: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AddressReplace(APIModel):
    line1: str
    line2: str | None = None
    city: str
    state: str | None = None
    postal_code: str | None = None
    country: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AddressPatch(APIModel):
    line1: str | None = None
    line2: str | None = None
    city: str | None = None
    state: str | None = None
    postal_code: str | None = None
    country: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AddressList(APIModel):
    items: list[AddressOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
