# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AgendaItemApprovalOut(APIModel):
    item_id: Any
    step_id: Any
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class AgendaItemApprovalCreate(APIModel):
    item_id: Any
    step_id: Any
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaItemApprovalReplace(APIModel):
    item_id: Any
    step_id: Any
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaItemApprovalPatch(APIModel):
    item_id: Any | None = None
    step_id: Any | None = None
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaItemApprovalList(APIModel):
    items: list[AgendaItemApprovalOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
