# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AgendaWorkflowOut(APIModel):
    name: str
    active: bool
    id: Any
    created_at: datetime
    updated_at: datetime

class AgendaWorkflowCreate(APIModel):
    name: str
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaWorkflowReplace(APIModel):
    name: str
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaWorkflowPatch(APIModel):
    name: str | None = None
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaWorkflowList(APIModel):
    items: list[AgendaWorkflowOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
