# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AgendaWorkflowStepOut(APIModel):
    workflow_id: Any
    step_no: int
    approver_type: str
    approver_id: Any | None = None
    rule: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class AgendaWorkflowStepCreate(APIModel):
    workflow_id: Any
    step_no: int | None = None
    approver_type: str
    approver_id: Any | None = None
    rule: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaWorkflowStepReplace(APIModel):
    workflow_id: Any
    step_no: int | None = None
    approver_type: str
    approver_id: Any | None = None
    rule: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaWorkflowStepPatch(APIModel):
    workflow_id: Any | None = None
    step_no: int | None = None
    approver_type: str | None = None
    approver_id: Any | None = None
    rule: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AgendaWorkflowStepList(APIModel):
    items: list[AgendaWorkflowStepOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
