# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AssetOut(APIModel):
    building_id: Any | None = None
    space_id: Any | None = None
    parent_asset_id: Any | None = None
    tag: str
    serial_no: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    category: str | None = None
    status: str | None = None
    install_date: date | None = None
    warranty_expires_at: date | None = None
    expected_life_months: int | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class AssetCreate(APIModel):
    building_id: Any | None = None
    space_id: Any | None = None
    parent_asset_id: Any | None = None
    tag: str
    serial_no: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    category: str | None = None
    status: str | None = None
    install_date: date | None = None
    warranty_expires_at: date | None = None
    expected_life_months: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssetReplace(APIModel):
    building_id: Any | None = None
    space_id: Any | None = None
    parent_asset_id: Any | None = None
    tag: str
    serial_no: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    category: str | None = None
    status: str | None = None
    install_date: date | None = None
    warranty_expires_at: date | None = None
    expected_life_months: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssetPatch(APIModel):
    building_id: Any | None = None
    space_id: Any | None = None
    parent_asset_id: Any | None = None
    tag: str | None = None
    serial_no: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    category: str | None = None
    status: str | None = None
    install_date: date | None = None
    warranty_expires_at: date | None = None
    expected_life_months: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssetList(APIModel):
    items: list[AssetOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
