# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AssignmentCategoryOut(APIModel):
    section_id: Any
    name: str
    weight: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class AssignmentCategoryCreate(APIModel):
    section_id: Any
    name: str
    weight: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssignmentCategoryReplace(APIModel):
    section_id: Any
    name: str
    weight: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssignmentCategoryPatch(APIModel):
    section_id: Any | None = None
    name: str | None = None
    weight: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AssignmentCategoryList(APIModel):
    items: list[AssignmentCategoryOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
