# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AttendanceCodeOut(APIModel):
    code: str
    description: str | None = None
    is_present: bool
    is_excused: bool
    created_at: datetime
    updated_at: datetime

class AttendanceCodeCreate(APIModel):
    description: str | None = None
    is_present: bool | None = None
    is_excused: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceCodeReplace(APIModel):
    description: str | None = None
    is_present: bool | None = None
    is_excused: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceCodePatch(APIModel):
    description: str | None = None
    is_present: bool | None = None
    is_excused: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceCodeList(APIModel):
    items: list[AttendanceCodeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
