# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class AttendanceDailySummaryOut(APIModel):
    student_id: Any
    date: date
    present_minutes: int
    absent_minutes: int
    tardy_minutes: int
    created_at: datetime
    updated_at: datetime
    id: Any

class AttendanceDailySummaryCreate(APIModel):
    student_id: Any
    date: date
    present_minutes: int | None = None
    absent_minutes: int | None = None
    tardy_minutes: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceDailySummaryReplace(APIModel):
    student_id: Any
    date: date
    present_minutes: int | None = None
    absent_minutes: int | None = None
    tardy_minutes: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceDailySummaryPatch(APIModel):
    student_id: Any | None = None
    date: date | None = None
    present_minutes: int | None = None
    absent_minutes: int | None = None
    tardy_minutes: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class AttendanceDailySummaryList(APIModel):
    items: list[AttendanceDailySummaryOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
