# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class BehaviorInterventionOut(APIModel):
    student_id: Any
    intervention: str
    start_date: date
    end_date: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class BehaviorInterventionCreate(APIModel):
    student_id: Any
    intervention: str
    start_date: date
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BehaviorInterventionReplace(APIModel):
    student_id: Any
    intervention: str
    start_date: date
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BehaviorInterventionPatch(APIModel):
    student_id: Any | None = None
    intervention: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BehaviorInterventionList(APIModel):
    items: list[BehaviorInterventionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
