# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class BehaviorCodeOut(APIModel):
    code: str
    description: str | None = None
    created_at: datetime
    updated_at: datetime

class BehaviorCodeCreate(APIModel):
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BehaviorCodeReplace(APIModel):
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BehaviorCodePatch(APIModel):
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BehaviorCodeList(APIModel):
    items: list[BehaviorCodeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
