# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class BusRouteOut(APIModel):
    name: str
    school_id: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class BusRouteCreate(APIModel):
    name: str
    school_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusRouteReplace(APIModel):
    name: str
    school_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusRoutePatch(APIModel):
    name: str | None = None
    school_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class BusRouteList(APIModel):
    items: list[BusRouteOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
