# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CalendarDayOut(APIModel):
    calendar_id: Any
    date: date
    day_type: str
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class CalendarDayCreate(APIModel):
    calendar_id: Any
    date: date
    day_type: str | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CalendarDayReplace(APIModel):
    calendar_id: Any
    date: date
    day_type: str | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CalendarDayPatch(APIModel):
    calendar_id: Any | None = None
    date: date | None = None
    day_type: str | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CalendarDayList(APIModel):
    items: list[CalendarDayOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
