# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CalendarOut(APIModel):
    school_id: Any
    name: str
    created_at: datetime
    updated_at: datetime
    id: Any

class CalendarCreate(APIModel):
    school_id: Any
    name: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CalendarReplace(APIModel):
    school_id: Any
    name: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CalendarPatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CalendarList(APIModel):
    items: list[CalendarOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
