# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ComplianceRecordOut(APIModel):
    building_id: Any | None = None
    asset_id: Any | None = None
    record_type: str
    authority: str | None = None
    identifier: str | None = None
    issued_at: date | None = None
    expires_at: date | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ComplianceRecordCreate(APIModel):
    building_id: Any | None = None
    asset_id: Any | None = None
    record_type: str
    authority: str | None = None
    identifier: str | None = None
    issued_at: date | None = None
    expires_at: date | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ComplianceRecordReplace(APIModel):
    building_id: Any | None = None
    asset_id: Any | None = None
    record_type: str
    authority: str | None = None
    identifier: str | None = None
    issued_at: date | None = None
    expires_at: date | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ComplianceRecordPatch(APIModel):
    building_id: Any | None = None
    asset_id: Any | None = None
    record_type: str | None = None
    authority: str | None = None
    identifier: str | None = None
    issued_at: date | None = None
    expires_at: date | None = None
    documents: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ComplianceRecordList(APIModel):
    items: list[ComplianceRecordOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
