# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ConsequenceOut(APIModel):
    incident_id: Any
    participant_id: Any
    consequence_code: str
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class ConsequenceCreate(APIModel):
    incident_id: Any
    participant_id: Any
    consequence_code: str
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsequenceReplace(APIModel):
    incident_id: Any
    participant_id: Any
    consequence_code: str
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsequencePatch(APIModel):
    incident_id: Any | None = None
    participant_id: Any | None = None
    consequence_code: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ConsequenceList(APIModel):
    items: list[ConsequenceOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
