# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ContactOut(APIModel):
    type: str
    value: str
    created_at: datetime
    updated_at: datetime
    id: Any

class ContactCreate(APIModel):
    type: str
    value: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ContactReplace(APIModel):
    type: str
    value: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ContactPatch(APIModel):
    type: str | None = None
    value: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ContactList(APIModel):
    items: list[ContactOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
