# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class CourseOut(APIModel):
    school_id: Any
    subject_id: Any | None = None
    name: str
    code: str | None = None
    credit_hours: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class CourseCreate(APIModel):
    school_id: Any
    subject_id: Any | None = None
    name: str
    code: str | None = None
    credit_hours: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CourseReplace(APIModel):
    school_id: Any
    subject_id: Any | None = None
    name: str
    code: str | None = None
    credit_hours: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CoursePatch(APIModel):
    school_id: Any | None = None
    subject_id: Any | None = None
    name: str | None = None
    code: str | None = None
    credit_hours: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class CourseList(APIModel):
    items: list[CourseOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
