# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DataSharingAgreementOut(APIModel):
    vendor: str
    scope: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class DataSharingAgreementCreate(APIModel):
    vendor: str
    scope: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DataSharingAgreementReplace(APIModel):
    vendor: str
    scope: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DataSharingAgreementPatch(APIModel):
    vendor: str | None = None
    scope: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DataSharingAgreementList(APIModel):
    items: list[DataSharingAgreementOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
