# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DeductionCodeOut(APIModel):
    code: str
    name: str
    pretax: bool
    vendor_id: Any | None = None
    attributes: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class DeductionCodeCreate(APIModel):
    code: str
    name: str
    pretax: bool | None = None
    vendor_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DeductionCodeReplace(APIModel):
    code: str
    name: str
    pretax: bool | None = None
    vendor_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DeductionCodePatch(APIModel):
    code: str | None = None
    name: str | None = None
    pretax: bool | None = None
    vendor_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DeductionCodeList(APIModel):
    items: list[DeductionCodeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
