# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DeliveryOut(APIModel):
    post_id: Any
    user_id: Any
    delivered_at: datetime | None = None
    medium: str | None = None
    status: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class DeliveryCreate(APIModel):
    post_id: Any
    user_id: Any
    delivered_at: datetime | None = None
    medium: str | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DeliveryReplace(APIModel):
    post_id: Any
    user_id: Any
    delivered_at: datetime | None = None
    medium: str | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DeliveryPatch(APIModel):
    post_id: Any | None = None
    user_id: Any | None = None
    delivered_at: datetime | None = None
    medium: str | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DeliveryList(APIModel):
    items: list[DeliveryOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
