# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DocumentVersionOut(APIModel):
    document_id: Any
    version_no: int
    file_id: Any
    checksum: str | None = None
    created_by: Any | None = None
    created_at: datetime
    published_at: datetime | None = None
    id: Any
    updated_at: datetime

class DocumentVersionCreate(APIModel):
    document_id: Any
    version_no: int | None = None
    file_id: Any
    checksum: str | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    published_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentVersionReplace(APIModel):
    document_id: Any
    version_no: int | None = None
    file_id: Any
    checksum: str | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    published_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentVersionPatch(APIModel):
    document_id: Any | None = None
    version_no: int | None = None
    file_id: Any | None = None
    checksum: str | None = None
    created_by: Any | None = None
    created_at: datetime | None = None
    published_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentVersionList(APIModel):
    items: list[DocumentVersionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
