# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DocumentLinkOut(APIModel):
    document_id: Any
    entity_type: str
    entity_id: Any
    created_at: datetime
    updated_at: datetime
    id: Any

class DocumentLinkCreate(APIModel):
    document_id: Any
    entity_type: str
    entity_id: Any
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentLinkReplace(APIModel):
    document_id: Any
    entity_type: str
    entity_id: Any
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentLinkPatch(APIModel):
    document_id: Any | None = None
    entity_type: str | None = None
    entity_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentLinkList(APIModel):
    items: list[DocumentLinkOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
