# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class DocumentActivityOut(APIModel):
    document_id: Any
    actor_id: Any | None = None
    action: str
    at: datetime
    meta: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class DocumentActivityCreate(APIModel):
    document_id: Any
    actor_id: Any | None = None
    action: str
    at: datetime | None = None
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentActivityReplace(APIModel):
    document_id: Any
    actor_id: Any | None = None
    action: str
    at: datetime | None = None
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentActivityPatch(APIModel):
    document_id: Any | None = None
    actor_id: Any | None = None
    action: str | None = None
    at: datetime | None = None
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class DocumentActivityList(APIModel):
    items: list[DocumentActivityOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
