# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class EarningCodeOut(APIModel):
    code: str
    name: str
    taxable: bool
    attributes: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class EarningCodeCreate(APIModel):
    code: str
    name: str
    taxable: bool | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EarningCodeReplace(APIModel):
    code: str
    name: str
    taxable: bool | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EarningCodePatch(APIModel):
    code: str | None = None
    name: str | None = None
    taxable: bool | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EarningCodeList(APIModel):
    items: list[EarningCodeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
