# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class EllPlanOut(APIModel):
    student_id: Any
    level: str | None = None
    effective_start: date
    effective_end: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class EllPlanCreate(APIModel):
    student_id: Any
    level: str | None = None
    effective_start: date
    effective_end: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EllPlanReplace(APIModel):
    student_id: Any
    level: str | None = None
    effective_start: date
    effective_end: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EllPlanPatch(APIModel):
    student_id: Any | None = None
    level: str | None = None
    effective_start: date | None = None
    effective_end: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EllPlanList(APIModel):
    items: list[EllPlanOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
