# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class EmbedOut(APIModel):
    provider: str
    url: str
    meta: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class EmbedCreate(APIModel):
    provider: str
    url: str
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmbedReplace(APIModel):
    provider: str
    url: str
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmbedPatch(APIModel):
    provider: str | None = None
    url: str | None = None
    meta: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmbedList(APIModel):
    items: list[EmbedOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
