# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class EmergencyContactOut(APIModel):
    person_id: Any
    contact_name: str
    relationship: str | None = None
    phone: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class EmergencyContactCreate(APIModel):
    person_id: Any
    contact_name: str
    relationship: str | None = None
    phone: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmergencyContactReplace(APIModel):
    person_id: Any
    contact_name: str
    relationship: str | None = None
    phone: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmergencyContactPatch(APIModel):
    person_id: Any | None = None
    contact_name: str | None = None
    relationship: str | None = None
    phone: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmergencyContactList(APIModel):
    items: list[EmergencyContactOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
