# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class EmployeeEarningOut(APIModel):
    run_id: Any
    employee_id: Any
    earning_code_id: Any
    hours: Decimal | None = None
    rate: Decimal | None = None
    amount: Decimal
    id: Any
    created_at: datetime
    updated_at: datetime

class EmployeeEarningCreate(APIModel):
    run_id: Any
    employee_id: Any
    earning_code_id: Any
    hours: Decimal | None = None
    rate: Decimal | None = None
    amount: Decimal
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmployeeEarningReplace(APIModel):
    run_id: Any
    employee_id: Any
    earning_code_id: Any
    hours: Decimal | None = None
    rate: Decimal | None = None
    amount: Decimal
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmployeeEarningPatch(APIModel):
    run_id: Any | None = None
    employee_id: Any | None = None
    earning_code_id: Any | None = None
    hours: Decimal | None = None
    rate: Decimal | None = None
    amount: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class EmployeeEarningList(APIModel):
    items: list[EmployeeEarningOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
