# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class ExternalIdOut(APIModel):
    entity_type: str
    entity_id: Any
    system: str
    external_id: str
    created_at: datetime
    updated_at: datetime
    id: Any

class ExternalIdCreate(APIModel):
    entity_type: str
    entity_id: Any
    system: str
    external_id: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ExternalIdReplace(APIModel):
    entity_type: str
    entity_id: Any
    system: str
    external_id: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ExternalIdPatch(APIModel):
    entity_type: str | None = None
    entity_id: Any | None = None
    system: str | None = None
    external_id: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class ExternalIdList(APIModel):
    items: list[ExternalIdOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
