# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FeeOut(APIModel):
    school_id: Any
    name: str
    amount: Decimal
    created_at: datetime
    updated_at: datetime
    id: Any

class FeeCreate(APIModel):
    school_id: Any
    name: str
    amount: Decimal
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FeeReplace(APIModel):
    school_id: Any
    name: str
    amount: Decimal
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FeePatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    amount: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FeeList(APIModel):
    items: list[FeeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
