# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FinalGradeOut(APIModel):
    student_id: Any
    section_id: Any
    grading_period_id: Any
    numeric_grade: Decimal | None = None
    letter_grade: str | None = None
    credits_earned: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class FinalGradeCreate(APIModel):
    student_id: Any
    section_id: Any
    grading_period_id: Any
    numeric_grade: Decimal | None = None
    letter_grade: str | None = None
    credits_earned: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FinalGradeReplace(APIModel):
    student_id: Any
    section_id: Any
    grading_period_id: Any
    numeric_grade: Decimal | None = None
    letter_grade: str | None = None
    credits_earned: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FinalGradePatch(APIModel):
    student_id: Any | None = None
    section_id: Any | None = None
    grading_period_id: Any | None = None
    numeric_grade: Decimal | None = None
    letter_grade: str | None = None
    credits_earned: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FinalGradeList(APIModel):
    items: list[FinalGradeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
