# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FiscalPeriodOut(APIModel):
    year_number: int
    period_no: int
    start_date: date
    end_date: date
    is_closed: bool
    id: uuid.UUID
    created_at: datetime
    updated_at: datetime


class FiscalPeriodCreate(APIModel):
    year_number: int
    period_no: int
    start_date: date
    end_date: date
    is_closed: bool | None = None


class FiscalPeriodReplace(APIModel):
    year_number: int
    period_no: int
    start_date: date
    end_date: date
    is_closed: bool | None = None


class FiscalPeriodPatch(APIModel):
    year_number: int | None = None
    period_no: int | None = None
    start_date: date | None = None
    end_date: date | None = None
    is_closed: bool | None = None


class FiscalPeriodList(APIModel):
    items: list[FiscalPeriodOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
