# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FloorOut(APIModel):
    building_id: Any
    level_code: str
    name: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class FloorCreate(APIModel):
    building_id: Any
    level_code: str
    name: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FloorReplace(APIModel):
    building_id: Any
    level_code: str
    name: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FloorPatch(APIModel):
    building_id: Any | None = None
    level_code: str | None = None
    name: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FloorList(APIModel):
    items: list[FloorOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
