# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class FolderOut(APIModel):
    org_id: Any
    parent_id: Any | None = None
    name: str
    is_public: bool
    sort_order: int | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class FolderCreate(APIModel):
    org_id: Any
    parent_id: Any | None = None
    name: str
    is_public: bool | None = None
    sort_order: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FolderReplace(APIModel):
    org_id: Any
    parent_id: Any | None = None
    name: str
    is_public: bool | None = None
    sort_order: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FolderPatch(APIModel):
    org_id: Any | None = None
    parent_id: Any | None = None
    name: str | None = None
    is_public: bool | None = None
    sort_order: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class FolderList(APIModel):
    items: list[FolderOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
