# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GLAccountSegmentOut(APIModel):
    account_id: Any
    segment_id: Any
    value_id: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class GLAccountSegmentCreate(APIModel):
    account_id: Any
    segment_id: Any
    value_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLAccountSegmentReplace(APIModel):
    account_id: Any
    segment_id: Any
    value_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLAccountSegmentPatch(APIModel):
    account_id: Any | None = None
    segment_id: Any | None = None
    value_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GLAccountSegmentList(APIModel):
    items: list[GLAccountSegmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
