# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GradingPeriodOut(APIModel):
    term_id: Any
    name: str
    start_date: date
    end_date: date
    created_at: datetime
    updated_at: datetime
    id: Any

class GradingPeriodCreate(APIModel):
    term_id: Any
    name: str
    start_date: date
    end_date: date
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradingPeriodReplace(APIModel):
    term_id: Any
    name: str
    start_date: date
    end_date: date
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradingPeriodPatch(APIModel):
    term_id: Any | None = None
    name: str | None = None
    start_date: date | None = None
    end_date: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradingPeriodList(APIModel):
    items: list[GradingPeriodOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
