# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GradeScaleBandOut(APIModel):
    grade_scale_id: Any
    label: str
    min_value: Decimal
    max_value: Decimal
    gpa_points: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class GradeScaleBandCreate(APIModel):
    grade_scale_id: Any
    label: str
    min_value: Decimal
    max_value: Decimal
    gpa_points: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeScaleBandReplace(APIModel):
    grade_scale_id: Any
    label: str
    min_value: Decimal
    max_value: Decimal
    gpa_points: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeScaleBandPatch(APIModel):
    grade_scale_id: Any | None = None
    label: str | None = None
    min_value: Decimal | None = None
    max_value: Decimal | None = None
    gpa_points: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeScaleBandList(APIModel):
    items: list[GradeScaleBandOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
