# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GradeLevelOut(APIModel):
    school_id: Any
    name: str
    ordinal: int | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class GradeLevelCreate(APIModel):
    school_id: Any
    name: str
    ordinal: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeLevelReplace(APIModel):
    school_id: Any
    name: str
    ordinal: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeLevelPatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    ordinal: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeLevelList(APIModel):
    items: list[GradeLevelOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
