# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GradeScaleOut(APIModel):
    school_id: Any
    name: str
    type: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class GradeScaleCreate(APIModel):
    school_id: Any
    name: str
    type: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeScaleReplace(APIModel):
    school_id: Any
    name: str
    type: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeScalePatch(APIModel):
    school_id: Any | None = None
    name: str | None = None
    type: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradeScaleList(APIModel):
    items: list[GradeScaleOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
