# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class GradebookEntryOut(APIModel):
    assignment_id: Any
    student_id: Any
    score: Decimal | None = None
    submitted_at: datetime | None = None
    late: bool
    created_at: datetime
    updated_at: datetime
    id: Any

class GradebookEntryCreate(APIModel):
    assignment_id: Any
    student_id: Any
    score: Decimal | None = None
    submitted_at: datetime | None = None
    late: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradebookEntryReplace(APIModel):
    assignment_id: Any
    student_id: Any
    score: Decimal | None = None
    submitted_at: datetime | None = None
    late: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradebookEntryPatch(APIModel):
    assignment_id: Any | None = None
    student_id: Any | None = None
    score: Decimal | None = None
    submitted_at: datetime | None = None
    late: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class GradebookEntryList(APIModel):
    items: list[GradebookEntryOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
