# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class HealthProfileOut(APIModel):
    student_id: Any
    allergies: str | None = None
    conditions: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class HealthProfileCreate(APIModel):
    student_id: Any
    allergies: str | None = None
    conditions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HealthProfileReplace(APIModel):
    student_id: Any
    allergies: str | None = None
    conditions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HealthProfilePatch(APIModel):
    student_id: Any | None = None
    allergies: str | None = None
    conditions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class HealthProfileList(APIModel):
    items: list[HealthProfileOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
