# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class IncidentOut(APIModel):
    school_id: Any | None = None
    occurred_at: datetime
    behavior_code: str
    description: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class IncidentCreate(APIModel):
    school_id: Any | None = None
    occurred_at: datetime
    behavior_code: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IncidentReplace(APIModel):
    school_id: Any | None = None
    occurred_at: datetime
    behavior_code: str
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IncidentPatch(APIModel):
    school_id: Any | None = None
    occurred_at: datetime | None = None
    behavior_code: str | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IncidentList(APIModel):
    items: list[IncidentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
