# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class IncidentParticipantOut(APIModel):
    incident_id: Any
    person_id: Any
    role: str
    id: Any
    created_at: datetime
    updated_at: datetime

class IncidentParticipantCreate(APIModel):
    incident_id: Any
    person_id: Any
    role: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IncidentParticipantReplace(APIModel):
    incident_id: Any
    person_id: Any
    role: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IncidentParticipantPatch(APIModel):
    incident_id: Any | None = None
    person_id: Any | None = None
    role: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class IncidentParticipantList(APIModel):
    items: list[IncidentParticipantOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
