# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class InitiativeOut(APIModel):
    objective_id: Any
    name: str
    description: str | None = None
    owner_id: Any | None = None
    due_date: date | None = None
    status: str | None = None
    priority: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class InitiativeCreate(APIModel):
    objective_id: Any
    name: str
    description: str | None = None
    owner_id: Any | None = None
    due_date: date | None = None
    status: str | None = None
    priority: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class InitiativeReplace(APIModel):
    objective_id: Any
    name: str
    description: str | None = None
    owner_id: Any | None = None
    due_date: date | None = None
    status: str | None = None
    priority: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class InitiativePatch(APIModel):
    objective_id: Any | None = None
    name: str | None = None
    description: str | None = None
    owner_id: Any | None = None
    due_date: date | None = None
    status: str | None = None
    priority: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class InitiativeList(APIModel):
    items: list[InitiativeOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
