# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class InvoiceOut(APIModel):
    student_id: Any
    issued_on: date
    due_on: date | None = None
    status: str
    created_at: datetime
    updated_at: datetime
    id: Any

class InvoiceCreate(APIModel):
    student_id: Any
    issued_on: date
    due_on: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class InvoiceReplace(APIModel):
    student_id: Any
    issued_on: date
    due_on: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class InvoicePatch(APIModel):
    student_id: Any | None = None
    issued_on: date | None = None
    due_on: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class InvoiceList(APIModel):
    items: list[InvoiceOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
