# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class JournalBatchOut(APIModel):
    batch_no: str
    description: str | None = None
    source: str | None = None
    status: str
    posted_at: datetime | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class JournalBatchCreate(APIModel):
    batch_no: str
    description: str | None = None
    source: str | None = None
    status: str | None = None
    posted_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalBatchReplace(APIModel):
    batch_no: str
    description: str | None = None
    source: str | None = None
    status: str | None = None
    posted_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalBatchPatch(APIModel):
    batch_no: str | None = None
    description: str | None = None
    source: str | None = None
    status: str | None = None
    posted_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class JournalBatchList(APIModel):
    items: list[JournalBatchOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
