# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class KPIOut(APIModel):
    goal_id: Any | None = None
    objective_id: Any | None = None
    name: str
    unit: str | None = None
    target: float | None = None
    baseline: float | None = None
    direction: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class KPICreate(APIModel):
    goal_id: Any | None = None
    objective_id: Any | None = None
    name: str
    unit: str | None = None
    target: float | None = None
    baseline: float | None = None
    direction: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class KPIReplace(APIModel):
    goal_id: Any | None = None
    objective_id: Any | None = None
    name: str
    unit: str | None = None
    target: float | None = None
    baseline: float | None = None
    direction: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class KPIPatch(APIModel):
    goal_id: Any | None = None
    objective_id: Any | None = None
    name: str | None = None
    unit: str | None = None
    target: float | None = None
    baseline: float | None = None
    direction: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class KPIList(APIModel):
    items: list[KPIOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
