# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class KPIDatapointOut(APIModel):
    kpi_id: Any
    as_of: date
    value: float
    note: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class KPIDatapointCreate(APIModel):
    kpi_id: Any
    as_of: date
    value: float
    note: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class KPIDatapointReplace(APIModel):
    kpi_id: Any
    as_of: date
    value: float
    note: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class KPIDatapointPatch(APIModel):
    kpi_id: Any | None = None
    as_of: date | None = None
    value: float | None = None
    note: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class KPIDatapointList(APIModel):
    items: list[KPIDatapointOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
