# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class LibraryCheckoutOut(APIModel):
    item_id: Any
    person_id: Any
    checked_out_on: date
    due_on: date
    returned_on: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class LibraryCheckoutCreate(APIModel):
    item_id: Any
    person_id: Any
    checked_out_on: date
    due_on: date
    returned_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryCheckoutReplace(APIModel):
    item_id: Any
    person_id: Any
    checked_out_on: date
    due_on: date
    returned_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryCheckoutPatch(APIModel):
    item_id: Any | None = None
    person_id: Any | None = None
    checked_out_on: date | None = None
    due_on: date | None = None
    returned_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryCheckoutList(APIModel):
    items: list[LibraryCheckoutOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
