# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class LibraryFineOut(APIModel):
    person_id: Any
    amount: Decimal
    reason: str | None = None
    assessed_on: date
    paid_on: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class LibraryFineCreate(APIModel):
    person_id: Any
    amount: Decimal
    reason: str | None = None
    assessed_on: date
    paid_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryFineReplace(APIModel):
    person_id: Any
    amount: Decimal
    reason: str | None = None
    assessed_on: date
    paid_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryFinePatch(APIModel):
    person_id: Any | None = None
    amount: Decimal | None = None
    reason: str | None = None
    assessed_on: date | None = None
    paid_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class LibraryFineList(APIModel):
    items: list[LibraryFineOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
