# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MaintenanceRequestOut(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    submitted_by_user_id: Any | None = None
    status: str
    priority: str | None = None
    summary: str
    description: str | None = None
    converted_work_order_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class MaintenanceRequestCreate(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    submitted_by_user_id: Any | None = None
    status: str | None = None
    priority: str | None = None
    summary: str
    description: str | None = None
    converted_work_order_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MaintenanceRequestReplace(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    submitted_by_user_id: Any | None = None
    status: str | None = None
    priority: str | None = None
    summary: str
    description: str | None = None
    converted_work_order_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MaintenanceRequestPatch(APIModel):
    school_id: Any | None = None
    building_id: Any | None = None
    space_id: Any | None = None
    asset_id: Any | None = None
    submitted_by_user_id: Any | None = None
    status: str | None = None
    priority: str | None = None
    summary: str | None = None
    description: str | None = None
    converted_work_order_id: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MaintenanceRequestList(APIModel):
    items: list[MaintenanceRequestOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
