# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MealTransactionOut(APIModel):
    account_id: Any
    transacted_at: datetime
    amount: Decimal
    description: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class MealTransactionCreate(APIModel):
    account_id: Any
    transacted_at: datetime
    amount: Decimal
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MealTransactionReplace(APIModel):
    account_id: Any
    transacted_at: datetime
    amount: Decimal
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MealTransactionPatch(APIModel):
    account_id: Any | None = None
    transacted_at: datetime | None = None
    amount: Decimal | None = None
    description: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MealTransactionList(APIModel):
    items: list[MealTransactionOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
