# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MealAccountOut(APIModel):
    student_id: Any
    balance: Decimal
    created_at: datetime
    updated_at: datetime
    id: Any

class MealAccountCreate(APIModel):
    student_id: Any
    balance: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MealAccountReplace(APIModel):
    student_id: Any
    balance: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MealAccountPatch(APIModel):
    student_id: Any | None = None
    balance: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MealAccountList(APIModel):
    items: list[MealAccountOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
