# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MedicationAdministrationOut(APIModel):
    student_id: Any
    medication_id: Any
    administered_at: datetime
    dose: str | None = None
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class MedicationAdministrationCreate(APIModel):
    student_id: Any
    medication_id: Any
    administered_at: datetime
    dose: str | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MedicationAdministrationReplace(APIModel):
    student_id: Any
    medication_id: Any
    administered_at: datetime
    dose: str | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MedicationAdministrationPatch(APIModel):
    student_id: Any | None = None
    medication_id: Any | None = None
    administered_at: datetime | None = None
    dose: str | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MedicationAdministrationList(APIModel):
    items: list[MedicationAdministrationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
