# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MedicationOut(APIModel):
    name: str
    instructions: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class MedicationCreate(APIModel):
    name: str
    instructions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MedicationReplace(APIModel):
    name: str
    instructions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MedicationPatch(APIModel):
    name: str | None = None
    instructions: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MedicationList(APIModel):
    items: list[MedicationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
