# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MeetingPublicationOut(APIModel):
    meeting_id: Any
    published_at: datetime
    public_url: str | None = None
    archive_url: str | None = None

class MeetingPublicationCreate(APIModel):
    published_at: datetime
    public_url: str | None = None
    archive_url: str | None = None

class MeetingPublicationReplace(APIModel):
    published_at: datetime
    public_url: str | None = None
    archive_url: str | None = None

class MeetingPublicationPatch(APIModel):
    published_at: datetime | None = None
    public_url: str | None = None
    archive_url: str | None = None

class MeetingPublicationList(APIModel):
    items: list[MeetingPublicationOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
