# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MeterOut(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str
    meter_type: str | None = None
    uom: str | None = None
    last_read_value: Decimal | None = None
    last_read_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class MeterCreate(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str
    meter_type: str | None = None
    uom: str | None = None
    last_read_value: Decimal | None = None
    last_read_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MeterReplace(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str
    meter_type: str | None = None
    uom: str | None = None
    last_read_value: Decimal | None = None
    last_read_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MeterPatch(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str | None = None
    meter_type: str | None = None
    uom: str | None = None
    last_read_value: Decimal | None = None
    last_read_at: datetime | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MeterList(APIModel):
    items: list[MeterOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
