# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MinutesOut(APIModel):
    meeting_id: Any
    author_id: Any | None = None
    content: str | None = None
    published_at: datetime | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class MinutesCreate(APIModel):
    meeting_id: Any
    author_id: Any | None = None
    content: str | None = None
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MinutesReplace(APIModel):
    meeting_id: Any
    author_id: Any | None = None
    content: str | None = None
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MinutesPatch(APIModel):
    meeting_id: Any | None = None
    author_id: Any | None = None
    content: str | None = None
    published_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MinutesList(APIModel):
    items: list[MinutesOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
