# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class MoveOrderOut(APIModel):
    project_id: Any | None = None
    person_id: Any | None = None
    from_space_id: Any | None = None
    to_space_id: Any | None = None
    move_date: date | None = None
    status: str | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class MoveOrderCreate(APIModel):
    project_id: Any | None = None
    person_id: Any | None = None
    from_space_id: Any | None = None
    to_space_id: Any | None = None
    move_date: date | None = None
    status: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MoveOrderReplace(APIModel):
    project_id: Any | None = None
    person_id: Any | None = None
    from_space_id: Any | None = None
    to_space_id: Any | None = None
    move_date: date | None = None
    status: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MoveOrderPatch(APIModel):
    project_id: Any | None = None
    person_id: Any | None = None
    from_space_id: Any | None = None
    to_space_id: Any | None = None
    move_date: date | None = None
    status: str | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class MoveOrderList(APIModel):
    items: list[MoveOrderOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
