# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class NurseVisitOut(APIModel):
    student_id: Any
    visited_at: datetime
    reason: str | None = None
    disposition: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class NurseVisitCreate(APIModel):
    student_id: Any
    visited_at: datetime
    reason: str | None = None
    disposition: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class NurseVisitReplace(APIModel):
    student_id: Any
    visited_at: datetime
    reason: str | None = None
    disposition: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class NurseVisitPatch(APIModel):
    student_id: Any | None = None
    visited_at: datetime | None = None
    reason: str | None = None
    disposition: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class NurseVisitList(APIModel):
    items: list[NurseVisitOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
