# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PaycheckOut(APIModel):
    run_id: Any
    employee_id: Any
    check_no: str | None = None
    gross_pay: Decimal
    net_pay: Decimal
    taxes: Any | None = None
    attributes: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PaycheckCreate(APIModel):
    run_id: Any
    employee_id: Any
    check_no: str | None = None
    gross_pay: Decimal
    net_pay: Decimal
    taxes: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PaycheckReplace(APIModel):
    run_id: Any
    employee_id: Any
    check_no: str | None = None
    gross_pay: Decimal
    net_pay: Decimal
    taxes: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PaycheckPatch(APIModel):
    run_id: Any | None = None
    employee_id: Any | None = None
    check_no: str | None = None
    gross_pay: Decimal | None = None
    net_pay: Decimal | None = None
    taxes: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PaycheckList(APIModel):
    items: list[PaycheckOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
