# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PayrollRunOut(APIModel):
    pay_period_id: Any
    run_no: int
    status: str
    created_by_user_id: Any | None = None
    posted_entry_id: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PayrollRunCreate(APIModel):
    pay_period_id: Any
    run_no: int | None = None
    status: str | None = None
    created_by_user_id: Any | None = None
    posted_entry_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PayrollRunReplace(APIModel):
    pay_period_id: Any
    run_no: int | None = None
    status: str | None = None
    created_by_user_id: Any | None = None
    posted_entry_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PayrollRunPatch(APIModel):
    pay_period_id: Any | None = None
    run_no: int | None = None
    status: str | None = None
    created_by_user_id: Any | None = None
    posted_entry_id: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PayrollRunList(APIModel):
    items: list[PayrollRunOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
