# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PeriodOut(APIModel):
    bell_schedule_id: Any
    name: str
    start_time: Any
    end_time: Any
    sequence: int | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PeriodCreate(APIModel):
    bell_schedule_id: Any
    name: str
    start_time: Any
    end_time: Any
    sequence: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PeriodReplace(APIModel):
    bell_schedule_id: Any
    name: str
    start_time: Any
    end_time: Any
    sequence: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PeriodPatch(APIModel):
    bell_schedule_id: Any | None = None
    name: str | None = None
    start_time: Any | None = None
    end_time: Any | None = None
    sequence: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PeriodList(APIModel):
    items: list[PeriodOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
