# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PersonAddressOut(APIModel):
    person_id: Any
    address_id: Any
    is_primary: bool
    created_at: datetime
    updated_at: datetime

class PersonAddressCreate(APIModel):
    is_primary: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonAddressReplace(APIModel):
    is_primary: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonAddressPatch(APIModel):
    is_primary: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PersonAddressList(APIModel):
    items: list[PersonAddressOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
