# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PlanFilterOut(APIModel):
    plan_id: Any
    name: str
    criteria: Any | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PlanFilterCreate(APIModel):
    plan_id: Any
    name: str
    criteria: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanFilterReplace(APIModel):
    plan_id: Any
    name: str
    criteria: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanFilterPatch(APIModel):
    plan_id: Any | None = None
    name: str | None = None
    criteria: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanFilterList(APIModel):
    items: list[PlanFilterOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
