# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PlanOut(APIModel):
    org_id: Any
    name: str
    cycle_start: date | None = None
    cycle_end: date | None = None
    status: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PlanCreate(APIModel):
    org_id: Any
    name: str
    cycle_start: date | None = None
    cycle_end: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanReplace(APIModel):
    org_id: Any
    name: str
    cycle_start: date | None = None
    cycle_end: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanPatch(APIModel):
    org_id: Any | None = None
    name: str | None = None
    cycle_start: date | None = None
    cycle_end: date | None = None
    status: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanList(APIModel):
    items: list[PlanOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
