# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PlanAlignmentOut(APIModel):
    agenda_item_id: Any | None = None
    policy_id: Any | None = None
    objective_id: Any | None = None
    note: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PlanAlignmentCreate(APIModel):
    agenda_item_id: Any | None = None
    policy_id: Any | None = None
    objective_id: Any | None = None
    note: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanAlignmentReplace(APIModel):
    agenda_item_id: Any | None = None
    policy_id: Any | None = None
    objective_id: Any | None = None
    note: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanAlignmentPatch(APIModel):
    agenda_item_id: Any | None = None
    policy_id: Any | None = None
    objective_id: Any | None = None
    note: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PlanAlignmentList(APIModel):
    items: list[PlanAlignmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
