# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PMPlanOut(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str
    frequency: str | None = None
    next_due_at: datetime | None = None
    last_completed_at: datetime | None = None
    active: bool
    procedure: Any | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class PMPlanCreate(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str
    frequency: str | None = None
    next_due_at: datetime | None = None
    last_completed_at: datetime | None = None
    active: bool | None = None
    procedure: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PMPlanReplace(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str
    frequency: str | None = None
    next_due_at: datetime | None = None
    last_completed_at: datetime | None = None
    active: bool | None = None
    procedure: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PMPlanPatch(APIModel):
    asset_id: Any | None = None
    building_id: Any | None = None
    name: str | None = None
    frequency: str | None = None
    next_due_at: datetime | None = None
    last_completed_at: datetime | None = None
    active: bool | None = None
    procedure: Any | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PMPlanList(APIModel):
    items: list[PMPlanOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
