# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyLegalRefOut(APIModel):
    policy_version_id: Any
    citation: str
    url: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PolicyLegalRefCreate(APIModel):
    policy_version_id: Any
    citation: str
    url: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyLegalRefReplace(APIModel):
    policy_version_id: Any
    citation: str
    url: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyLegalRefPatch(APIModel):
    policy_version_id: Any | None = None
    citation: str | None = None
    url: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyLegalRefList(APIModel):
    items: list[PolicyLegalRefOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
