# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyApprovalOut(APIModel):
    policy_version_id: Any
    step_id: Any
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    id: Any
    created_at: datetime
    updated_at: datetime

class PolicyApprovalCreate(APIModel):
    policy_version_id: Any
    step_id: Any
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyApprovalReplace(APIModel):
    policy_version_id: Any
    step_id: Any
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyApprovalPatch(APIModel):
    policy_version_id: Any | None = None
    step_id: Any | None = None
    approver_id: Any | None = None
    decision: str | None = None
    decided_at: datetime | None = None
    comment: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyApprovalList(APIModel):
    items: list[PolicyApprovalOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
