# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyWorkflowOut(APIModel):
    policy_id: Any
    name: str
    active: bool
    id: Any
    created_at: datetime
    updated_at: datetime

class PolicyWorkflowCreate(APIModel):
    policy_id: Any
    name: str
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyWorkflowReplace(APIModel):
    policy_id: Any
    name: str
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyWorkflowPatch(APIModel):
    policy_id: Any | None = None
    name: str | None = None
    active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyWorkflowList(APIModel):
    items: list[PolicyWorkflowOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
