# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class PolicyCommentOut(APIModel):
    policy_version_id: Any
    user_id: Any | None = None
    text: str
    visibility: str
    id: Any
    created_at: datetime
    updated_at: datetime

class PolicyCommentCreate(APIModel):
    policy_version_id: Any
    user_id: Any | None = None
    text: str
    visibility: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyCommentReplace(APIModel):
    policy_version_id: Any
    user_id: Any | None = None
    text: str
    visibility: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyCommentPatch(APIModel):
    policy_version_id: Any | None = None
    user_id: Any | None = None
    text: str | None = None
    visibility: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class PolicyCommentList(APIModel):
    items: list[PolicyCommentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
