# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SisImportJobOut(APIModel):
    source: str
    status: str
    started_at: datetime
    finished_at: datetime | None = None
    counts: Any | None = None
    error_log: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SisImportJobCreate(APIModel):
    source: str
    status: str | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None
    counts: Any | None = None
    error_log: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SisImportJobReplace(APIModel):
    source: str
    status: str | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None
    counts: Any | None = None
    error_log: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SisImportJobPatch(APIModel):
    source: str | None = None
    status: str | None = None
    started_at: datetime | None = None
    finished_at: datetime | None = None
    counts: Any | None = None
    error_log: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SisImportJobList(APIModel):
    items: list[SisImportJobOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
