# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class SpaceOut(APIModel):
    building_id: Any
    floor_id: Any | None = None
    code: str
    name: str | None = None
    space_type: str | None = None
    area_sqft: Decimal | None = None
    capacity: int | None = None
    attributes: Any | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class SpaceCreate(APIModel):
    building_id: Any
    floor_id: Any | None = None
    code: str
    name: str | None = None
    space_type: str | None = None
    area_sqft: Decimal | None = None
    capacity: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpaceReplace(APIModel):
    building_id: Any
    floor_id: Any | None = None
    code: str
    name: str | None = None
    space_type: str | None = None
    area_sqft: Decimal | None = None
    capacity: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpacePatch(APIModel):
    building_id: Any | None = None
    floor_id: Any | None = None
    code: str | None = None
    name: str | None = None
    space_type: str | None = None
    area_sqft: Decimal | None = None
    capacity: int | None = None
    attributes: Any | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class SpaceList(APIModel):
    items: list[SpaceOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
