# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StaffOut(APIModel):
    employee_number: str | None = None
    title: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class StaffCreate(APIModel):
    employee_number: str | None = None
    title: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StaffReplace(APIModel):
    employee_number: str | None = None
    title: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StaffPatch(APIModel):
    employee_number: str | None = None
    title: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StaffList(APIModel):
    items: list[StaffOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
