# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StandardizedTestOut(APIModel):
    name: str
    subject: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class StandardizedTestCreate(APIModel):
    name: str
    subject: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StandardizedTestReplace(APIModel):
    name: str
    subject: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StandardizedTestPatch(APIModel):
    name: str | None = None
    subject: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StandardizedTestList(APIModel):
    items: list[StandardizedTestOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
