# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StudentSectionEnrollmentOut(APIModel):
    student_id: Any
    section_id: Any
    added_on: date
    dropped_on: date | None = None
    seat_time_minutes: int | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class StudentSectionEnrollmentCreate(APIModel):
    student_id: Any
    section_id: Any
    added_on: date
    dropped_on: date | None = None
    seat_time_minutes: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentSectionEnrollmentReplace(APIModel):
    student_id: Any
    section_id: Any
    added_on: date
    dropped_on: date | None = None
    seat_time_minutes: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentSectionEnrollmentPatch(APIModel):
    student_id: Any | None = None
    section_id: Any | None = None
    added_on: date | None = None
    dropped_on: date | None = None
    seat_time_minutes: int | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentSectionEnrollmentList(APIModel):
    items: list[StudentSectionEnrollmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
