# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class StudentSchoolEnrollmentOut(APIModel):
    student_id: Any
    school_id: Any
    entry_date: date
    exit_date: date | None = None
    status: str
    exit_reason: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class StudentSchoolEnrollmentCreate(APIModel):
    student_id: Any
    school_id: Any
    entry_date: date
    exit_date: date | None = None
    status: str | None = None
    exit_reason: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentSchoolEnrollmentReplace(APIModel):
    student_id: Any
    school_id: Any
    entry_date: date
    exit_date: date | None = None
    status: str | None = None
    exit_reason: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentSchoolEnrollmentPatch(APIModel):
    student_id: Any | None = None
    school_id: Any | None = None
    entry_date: date | None = None
    exit_date: date | None = None
    status: str | None = None
    exit_reason: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class StudentSchoolEnrollmentList(APIModel):
    items: list[StudentSchoolEnrollmentOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
