# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class TagOut(APIModel):
    label: str
    id: Any
    created_at: datetime
    updated_at: datetime

class TagCreate(APIModel):
    label: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TagReplace(APIModel):
    label: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TagPatch(APIModel):
    label: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TagList(APIModel):
    items: list[TagOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
