# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class TicketOut(APIModel):
    order_id: Any
    ticket_type_id: Any
    serial_no: int
    price_cents: int
    holder_person_id: Any | None = None
    qr_code: str | None = None
    status: str
    issued_at: datetime
    checked_in_at: datetime | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class TicketCreate(APIModel):
    order_id: Any
    ticket_type_id: Any
    serial_no: int
    price_cents: int | None = None
    holder_person_id: Any | None = None
    qr_code: str | None = None
    status: str | None = None
    issued_at: datetime | None = None
    checked_in_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketReplace(APIModel):
    order_id: Any
    ticket_type_id: Any
    serial_no: int
    price_cents: int | None = None
    holder_person_id: Any | None = None
    qr_code: str | None = None
    status: str | None = None
    issued_at: datetime | None = None
    checked_in_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketPatch(APIModel):
    order_id: Any | None = None
    ticket_type_id: Any | None = None
    serial_no: int | None = None
    price_cents: int | None = None
    holder_person_id: Any | None = None
    qr_code: str | None = None
    status: str | None = None
    issued_at: datetime | None = None
    checked_in_at: datetime | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TicketList(APIModel):
    items: list[TicketOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
