# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class TranscriptLineOut(APIModel):
    student_id: Any
    course_id: Any | None = None
    term_id: Any | None = None
    credits_attempted: Decimal | None = None
    credits_earned: Decimal | None = None
    final_letter: str | None = None
    final_numeric: Decimal | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class TranscriptLineCreate(APIModel):
    student_id: Any
    course_id: Any | None = None
    term_id: Any | None = None
    credits_attempted: Decimal | None = None
    credits_earned: Decimal | None = None
    final_letter: str | None = None
    final_numeric: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TranscriptLineReplace(APIModel):
    student_id: Any
    course_id: Any | None = None
    term_id: Any | None = None
    credits_attempted: Decimal | None = None
    credits_earned: Decimal | None = None
    final_letter: str | None = None
    final_numeric: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TranscriptLinePatch(APIModel):
    student_id: Any | None = None
    course_id: Any | None = None
    term_id: Any | None = None
    credits_attempted: Decimal | None = None
    credits_earned: Decimal | None = None
    final_letter: str | None = None
    final_numeric: Decimal | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class TranscriptLineList(APIModel):
    items: list[TranscriptLineOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
