# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class UserOut(APIModel):
    username: str
    email: str
    created_at: datetime
    id: Any
    updated_at: datetime

class UserCreate(APIModel):
    username: str
    email: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class UserReplace(APIModel):
    username: str
    email: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class UserPatch(APIModel):
    username: str | None = None
    email: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class UserList(APIModel):
    items: list[UserOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
