# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional
from datetime import datetime
import uuid

from pydantic import Field
from OSSS.schemas.base import APIModel


class UserAccountOut(APIModel):
    person_id: uuid.UUID
    username: str
    password_hash: str | None = None  # NOTE: consider excluding from outward responses
    is_active: bool
    created_at: datetime
    updated_at: datetime
    id: uuid.UUID


class UserAccountCreate(APIModel):
    person_id: uuid.UUID
    username: str
    password_hash: str | None = None
    # DB defaults these; allow client to omit
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


class UserAccountReplace(APIModel):
    person_id: uuid.UUID
    username: str
    password_hash: str | None = None
    # Keep parity with create semantics
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


class UserAccountPatch(APIModel):
    person_id: uuid.UUID | None = None
    username: str | None = None
    password_hash: str | None = None
    is_active: bool | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None


class UserAccountList(APIModel):
    items: list[UserAccountOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
