# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class VendorOut(APIModel):
    name: str
    contact: Any | None = None
    active: bool
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class VendorCreate(APIModel):
    name: str
    contact: Any | None = None
    active: bool | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class VendorReplace(APIModel):
    name: str
    contact: Any | None = None
    active: bool | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class VendorPatch(APIModel):
    name: str | None = None
    contact: Any | None = None
    active: bool | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class VendorList(APIModel):
    items: list[VendorOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
