# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class VoteOut(APIModel):
    motion_id: Any
    voter_id: Any
    value: str
    id: Any
    created_at: datetime
    updated_at: datetime

class VoteCreate(APIModel):
    motion_id: Any
    voter_id: Any
    value: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class VoteReplace(APIModel):
    motion_id: Any
    voter_id: Any
    value: str
    created_at: datetime | None = None
    updated_at: datetime | None = None

class VotePatch(APIModel):
    motion_id: Any | None = None
    voter_id: Any | None = None
    value: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class VoteList(APIModel):
    items: list[VoteOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
