# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class WaiverOut(APIModel):
    student_id: Any
    reason: str | None = None
    amount: Decimal | None = None
    granted_on: date | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class WaiverCreate(APIModel):
    student_id: Any
    reason: str | None = None
    amount: Decimal | None = None
    granted_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WaiverReplace(APIModel):
    student_id: Any
    reason: str | None = None
    amount: Decimal | None = None
    granted_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WaiverPatch(APIModel):
    student_id: Any | None = None
    reason: str | None = None
    amount: Decimal | None = None
    granted_on: date | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WaiverList(APIModel):
    items: list[WaiverOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
