# Auto-generated by OSSS.schemas.codegen — DO NOT EDIT BY HAND
from __future__ import annotations
from typing import Optional, Any, List
from datetime import date, datetime
from decimal import Decimal
import uuid
from pydantic import Field
from OSSS.schemas.base import APIModel


class WorkOrderTimeLogOut(APIModel):
    work_order_id: Any
    user_id: Any | None = None
    started_at: datetime | None = None
    ended_at: datetime | None = None
    hours: Decimal | None = None
    hourly_rate: Decimal | None = None
    cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime
    updated_at: datetime
    id: Any

class WorkOrderTimeLogCreate(APIModel):
    work_order_id: Any
    user_id: Any | None = None
    started_at: datetime | None = None
    ended_at: datetime | None = None
    hours: Decimal | None = None
    hourly_rate: Decimal | None = None
    cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderTimeLogReplace(APIModel):
    work_order_id: Any
    user_id: Any | None = None
    started_at: datetime | None = None
    ended_at: datetime | None = None
    hours: Decimal | None = None
    hourly_rate: Decimal | None = None
    cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderTimeLogPatch(APIModel):
    work_order_id: Any | None = None
    user_id: Any | None = None
    started_at: datetime | None = None
    ended_at: datetime | None = None
    hours: Decimal | None = None
    hourly_rate: Decimal | None = None
    cost: Decimal | None = None
    notes: str | None = None
    created_at: datetime | None = None
    updated_at: datetime | None = None

class WorkOrderTimeLogList(APIModel):
    items: list[WorkOrderTimeLogOut]
    total: int | None = None
    skip: int = 0
    limit: int = 100
