apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: osss-web:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              valueFrom: { configMapKeyRef: { name: osss-config, key: WEB_PORT } }
            - name: API_URL
              value: "http://api:8081"
            - name: NEXT_PUBLIC_KEYCLOAK_URL
              valueFrom: { configMapKeyRef: { name: osss-config, key: KEYCLOAK_URL } }
            - name: NEXT_PUBLIC_KEYCLOAK_REALM
              valueFrom: { configMapKeyRef: { name: osss-config, key: KEYCLOAK_REALM } }
            - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
              valueFrom: { configMapKeyRef: { name: osss-config, key: KEYCLOAK_CLIENT_ID } }
          ports:
            - containerPort: 3000
              name: http
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 15
            periodSeconds: 20
