# /work/config_files/filebeat/filebeat.podman.yml
filebeat.inputs:
  - type: container
    id: podman-container-logs
    stream: all
    # Podman writes one ctr.log per container:
    paths:
      - /var/lib/containers/storage/overlay-containers/*/userdata/ctr.log
    parsers:
      - container: {}   # parse timestamp/stream JSON lines when present

    processors:
      - add_docker_metadata:
          host: "unix:///var/run/podman.sock"
          match_fields: ["container.id"]
          match_pids: ["process.pid", "process.parent.pid"]
          cleanup_timeout: 60s

# Ship straight to ES
output.elasticsearch:
  hosts: [ "http://host.containers.internal:9200" ]
  api_key: "${ELASTIC_API_KEY}"

# (optional) Kibana
setup.kibana.host: "http://host.containers.internal:5601"

http.enabled: true
http.host: 0.0.0.0
http.port: 5066
logging.level: debug

# fast flush for tiny batches
queue.mem:
  flush.min_events: 1
  flush.timeout: 1s
