FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONPATH=/app
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
COPY pyproject.toml /app/

RUN pip install --no-cache-dir -U pip setuptools wheel \
 && pip install --no-cache-dir .

COPY app /app/app
COPY alembic.ini /app/
COPY alembic /app/alembic
EXPOSE 8000

