
MANUAL_FK_MAP = {'academic_terms': {'school_id': ('schools', 'id')},
 'accommodations': {'iep_plan_id': ('iep_plans', 'id')},
 'activities': {'school_id': ('schools', 'id')},
 'agenda_item_approvals': {'approver_id': ('users', 'id'),
                           'item_id': ('agenda_items', 'id'),
                           'step_id': ('agenda_workflow_steps', 'id')},
 'agenda_item_files': {'agenda_item_id': ('agenda_items', 'id'),
                       'file_id': ('files', 'id')},
 'agenda_items': {'meeting_id': ('meetings', 'id'),
                  'parent_id': ('agenda_items', 'id')},
 'agenda_workflow_steps': {'workflow_id': ('agenda_workflows', 'id')},
 'alignments': {'curriculum_version_id': ('curriculum_versions', 'id'),
                'requirement_id': ('requirements', 'id')},
 'announcements': {'course_id': ('courses', 'id'), 'user_id': ('users', 'id')},
 'approvals': {'proposal_id': ('proposals', 'id')},
 'asset_parts': {'asset_id': ('assets', 'id'), 'part_id': ('parts', 'id')},
 'assets': {'building_id': ('buildings', 'id'),
            'parent_asset_id': ('assets', 'id'),
            'space_id': ('spaces', 'id')},
 'assignment_categories': {'section_id': ('course_sections', 'id')},
 'assignments': {'category_id': ('assignment_categories', 'id'),
                 'section_id': ('course_sections', 'id')},
 'attendance': {'meeting_id': ('meetings', 'id'), 'user_id': ('users', 'id')},
 'attendance_daily_summary': {'student_id': ('students', 'id')},
 'attendance_events': {'code': ('attendance_codes', 'code'),
                       'section_meeting_id': ('section_meetings', 'id'),
                       'student_id': ('students', 'id')},
 'audit_logs': {'actor_id': ('user_accounts', 'id')},
 'behavior_interventions': {'student_id': ('students', 'id')},
 'bell_schedules': {'school_id': ('schools', 'id')},
 'buildings': {'facility_id': ('facilities', 'id')},
 'bus_routes': {'school_id': ('schools', 'id')},
 'bus_stop_times': {'route_id': ('bus_routes', 'id'),
                    'stop_id': ('bus_stops', 'id')},
 'bus_stops': {'route_id': ('bus_routes', 'id')},
 'calendar_days': {'calendar_id': ('calendars', 'id')},
 'calendars': {'school_id': ('schools', 'id')},
 'camp_registrations': {'camp_id': ('camps', 'id'),
                        'school_id': ('schools', 'id')},
 'camps': {'school_id': ('schools', 'id')},
 'channels': {'org_id': ('organizations', 'id')},
 'class_ranks': {'school_id': ('schools', 'id'),
                 'student_id': ('students', 'id'),
                 'term_id': ('academic_terms', 'id')},
 'committees': {'organization_id': ('organizations', 'id'),
                'school_id': ('schools', 'id')},
 'compliance_records': {'asset_id': ('assets', 'id'),
                        'building_id': ('buildings', 'id')},
 'concession_items': {'school_id': ('schools', 'id'),
                      'stand_id': ('concession_stands', 'id')},
 'concession_sale_items': {'item_id': ('concession_items', 'id'),
                           'sale_id': ('concession_sales', 'id')},
 'concession_sales': {'event_id': ('events', 'id'),
                      'stand_id': ('concession_stands', 'id')},
 'consents': {'person_id': ('persons', 'id')},
 'consequences': {'consequence_code': ('consequence_types', 'code'),
                  'incident_id': ('incidents', 'id'),
                  'participant_id': ('incident_participants', 'id')},
 'course_prerequisites': {'course_id': ('courses', 'id'),
                          'prereq_course_id': ('courses', 'id')},
 'course_sections': {'course_id': ('courses', 'id'),
                     'school_id': ('schools', 'id'),
                     'term_id': ('academic_terms', 'id')},
 'course_students': {'course_id': ('courses', 'id'),
                     'user_id': ('user_profiles', 'id')},
 "course_teachers": {
     "course_id": ("courses", "id"),
     "user_id": ("user_profiles", "id"),
 },
 'courses': {'calendar_id': ('calendars', 'id'),
             'school_id': ('schools', 'id'),
             'subject_id': ('subjects', 'id'),
             'user_id': ('users', 'id')},
 'coursework': {'course_id': ('courses', 'id'),
                'topic_id': ('topics', 'id'),
                'user_id': ('users', 'id')},
 'curricula': {'organization_id': ('organizations', 'id'),
               'proposal_id': ('proposals', 'id')},
 'curriculum_units': {'curriculum_id': ('curricula', 'id')},
 'curriculum_versions': {'curriculum_id': ('curricula', 'id')},
 'deduction_codes': {'vendor_id': ('vendors', 'id')},
 'deliveries': {'post_id': ('posts', 'id'), 'user_id': ('users', 'id')},
 'department_position_index': {'department_id': ('departments', 'id'),
                               'position_id': ('hr_positions', 'id')},
 'departments': {'school_id': ('schools', 'id')},
 'document_activity': {'actor_id': ('users', 'id'),
                       'document_id': ('documents', 'id')},
 'document_links': {'document_id': ('documents', 'id')},
 'document_notifications': {'document_id': ('documents', 'id'),
                            'user_id': ('users', 'id')},
 'document_search_index': {'document_id': ('documents', 'id')},
 'document_versions': {'created_by': ('users', 'id'),
                       'document_id': ('documents', 'id'),
                       'file_id': ('files', 'id')},
 'documents': {'current_version_id': ('document_versions', 'id'),
               'folder_id': ('folders', 'id')},
 'donations': {'campaign_id': ('fundraising_campaigns', 'id'),
               'school_id': ('schools', 'id')},
 'ell_plans': {'student_id': ('students', 'id')},
 'emergency_contacts': {'person_id': ('persons', 'id')},
 'employee_deductions': {'deduction_code_id': ('deduction_codes', 'id'),
                         'employee_id': ('hr_employees', 'id'),
                         'run_id': ('payroll_runs', 'id')},
 'employee_earnings': {'earning_code_id': ('earning_codes', 'id'),
                       'employee_id': ('hr_employees', 'id'),
                       'run_id': ('payroll_runs', 'id')},
 'entity_tags': {'tag_id': ('tags', 'id')},
 'evaluation_assignments': {'cycle_id': ('evaluation_cycles', 'id'),
                            'evaluator_user_id': ('users', 'id'),
                            'subject_user_id': ('users', 'id'),
                            'template_id': ('evaluation_templates', 'id')},
 'evaluation_cycles': {'org_id': ('organizations', 'id')},
 'evaluation_files': {'assignment_id': ('evaluation_assignments', 'id'),
                      'file_id': ('files', 'id')},
 'evaluation_questions': {'section_id': ('evaluation_sections', 'id')},
 'evaluation_reports': {'cycle_id': ('evaluation_cycles', 'id'),
                        'file_id': ('files', 'id')},
 'evaluation_responses': {'assignment_id': ('evaluation_assignments', 'id'),
                          'question_id': ('evaluation_questions', 'id')},
 'evaluation_sections': {'template_id': ('evaluation_templates', 'id')},
 'evaluation_signoffs': {'assignment_id': ('evaluation_assignments', 'id'),
                         'signer_id': ('users', 'id')},
 'events': {'activity_id': ('activities', 'id'),
            'school_id': ('schools', 'id')},
 'facilities': {'school_id': ('schools', 'id')},
 'family_portal_access': {'guardian_id': ('guardians', 'id'),
                          'student_id': ('students', 'id')},
 'fan_app_settings': {'school_id': ('schools', 'id')},
 'fan_pages': {'school_id': ('schools', 'id')},
 'feature_flags': {'org_id': ('organizations', 'id')},
 'fees': {'school_id': ('schools', 'id')},
 'files': {'created_by': ('users', 'id')},
 'final_grades': {'grading_period_id': ('grading_periods', 'id'),
                  'section_id': ('course_sections', 'id'),
                  'student_id': ('students', 'id')},
 'floors': {'building_id': ('buildings', 'id')},
 'folders': {'org_id': ('organizations', 'id'), 'parent_id': ('folders', 'id')},
 'fundraising_campaigns': {'school_id': ('schools', 'id')},
 'game_official_contracts': {'game_id': ('games', 'id'),
                             'official_id': ('officials', 'id')},
 'game_programs': {'game_id': ('games', 'id')},
 'game_reports': {'game_id': ('games', 'id')},
 'games': {'season_id': ('seasons', 'id'), 'team_id': ('teams', 'id')},
 'gl_account_balances': {'account_id': ('gl_accounts', 'id'),
                         'fiscal_period_id': ('fiscal_periods', 'id')},
 'gl_account_segments': {'segment_id': ('gl_segments', 'id'),
                         'value_id': ('gl_segment_values', 'id')},
 'gl_segment_values': {'segment_id': ('gl_segments', 'id')},
 'goals': {'plan_id': ('plans', 'id')},
 'governing_bodies': {'org_id': ('organizations', 'id')},
 'gpa_calculations': {'student_id': ('students', 'id'),
                      'term_id': ('academic_terms', 'id')},
 'grade_levels': {'school_id': ('schools', 'id')},
 'grade_scale_bands': {'grade_scale_id': ('grade_scales', 'id')},
 'grade_scales': {'school_id': ('schools', 'id')},
 'gradebook_entries': {'assignment_id': ('assignments', 'id'),
                       'student_id': ('students', 'id')},
 'grading_periods': {'term_id': ('academic_terms', 'id')},
 'guardian_invitations': {'student_user_id': ('user_profiles', 'id'),
                          'user_id': ('users', 'id')},
 'guardians': {'guardian_user_id': ('user_profiles', 'id'),
               'student_user_id': ('user_profiles', 'id')},
 'health_profiles': {'student_id': ('students', 'id')},
 'hr_employees': {'department_segment_id': ('gl_segments', 'id'),
                  'person_id': ('persons', 'id'),
                  'primary_school_id': ('schools', 'id')},
 'hr_position_assignments': {'employee_id': ('hr_employees', 'id'),
                             'position_id': ('hr_positions', 'id')},
 'hr_positions': {'department_segment_id': ('gl_segments', 'id')},
 'iep_plans': {'special_ed_case_id': ('special_education_cases', 'id')},
 'immunization_records': {'immunization_id': ('immunizations', 'id'),
                          'student_id': ('students', 'id')},
 'incident_participants': {'incident_id': ('incidents', 'id'),
                           'person_id': ('persons', 'id')},
 'incidents': {'behavior_code': ('behavior_codes', 'code'),
               'school_id': ('schools', 'id')},
 'initiatives': {'objective_id': ('objectives', 'id'),
                 'owner_id': ('users', 'id')},
 'invoices': {'student_id': ('students', 'id')},
 'journal_entries': {'batch_id': ('journal_batches', 'id'),
                     'fiscal_period_id': ('fiscal_periods', 'id')},
 'journal_entry_lines': {'account_id': ('gl_accounts', 'id'),
                         'entry_id': ('journal_entries', 'id')},
 'kpi_datapoints': {'kpi_id': ('kpis', 'id')},
 'kpis': {'goal_id': ('goals', 'id'), 'objective_id': ('objectives', 'id')},
 'leases': {'building_id': ('buildings', 'id')},
 'library_checkouts': {'item_id': ('library_items', 'id'),
                       'person_id': ('persons', 'id')},
 'library_fines': {'person_id': ('persons', 'id')},
 'library_holds': {'item_id': ('library_items', 'id'),
                   'person_id': ('persons', 'id')},
 'library_items': {'school_id': ('schools', 'id')},
 'live_scoring': {'game_id': ('games', 'id')},
 'maintenance_requests': {'asset_id': ('assets', 'id'),
                          'building_id': ('buildings', 'id'),
                          'converted_work_order_id': ('work_orders', 'id'),
                          'school_id': ('schools', 'id'),
                          'space_id': ('spaces', 'id'),
                          'submitted_by_user_id': ('users', 'id')},
 'manual_stats': {'game_id': ('games', 'id')},
 'materials': {'announcement_id': ('announcements', 'id'),
               'coursework_id': ('coursework', 'id')},
 'meal_accounts': {'student_id': ('students', 'id')},
 'meal_eligibility_statuses': {'student_id': ('students', 'id')},
 'meal_transactions': {'account_id': ('meal_accounts', 'id')},
 'medication_administrations': {'medication_id': ('medications', 'id'),
                                'student_id': ('students', 'id')},
 'meeting_documents': {'document_id': ('documents', 'id'),
                       'meeting_id': ('meetings', 'id')},
 'meeting_files': {'file_id': ('files', 'id'),
                   'meeting_id': ('meetings', 'id')},
 'meeting_permissions': {'meeting_id': ('meetings', 'id'),
                         'user_id': ('users', 'id')},
 'meeting_publications': {'meeting_id': ('meetings', 'id')},
 'meeting_search_index': {'meeting_id': ('meetings', 'id')},
 'meetings': {'committee_id': ('committees', 'id'),
              'governing_body_id': ('governing_bodies', 'id'),
              'org_id': ('organizations', 'id')},
 'memberships': {'committee_id': ('committees', 'id'),
                 'person_id': ('persons', 'id')},
 'message_recipients': {'message_id': ('messages', 'id'),
                        'person_id': ('persons', 'id')},
 'messages': {'sender_id': ('user_accounts', 'id')},
 'meters': {'asset_id': ('assets', 'id'), 'building_id': ('buildings', 'id')},
 'minutes': {'author_id': ('users', 'id'), 'meeting_id': ('meetings', 'id')},
 'motions': {'agenda_item_id': ('agenda_items', 'id'),
             'moved_by_id': ('users', 'id'),
             'seconded_by_id': ('users', 'id')},
 'move_orders': {'from_space_id': ('spaces', 'id'),
                 'person_id': ('users', 'id'),
                 'project_id': ('projects', 'id'),
                 'to_space_id': ('spaces', 'id')},
 'notifications': {'user_id': ('users', 'id')},
 'nurse_visits': {'student_id': ('students', 'id')},
 'objectives': {'goal_id': ('goals', 'id')},
 'order_line_items': {'order_id': ('orders', 'id'),
                      'ticket_type_id': ('ticket_types', 'id')},
 'orders': {'event_id': ('events', 'id'),
            'purchaser_user_id': ('users', 'id'),
            'school_id': ('schools', 'id')},
 'pages': {'channel_id': ('channels', 'id')},
 'part_locations': {'building_id': ('buildings', 'id'),
                    'part_id': ('parts', 'id'),
                    'space_id': ('spaces', 'id')},
 'passes': {'school_id': ('schools', 'id')},
 'paychecks': {'employee_id': ('hr_employees', 'id'),
               'run_id': ('payroll_runs', 'id')},
 'payments': {'invoice_id': ('invoices', 'id')},
 'payroll_runs': {'created_by_user_id': ('users', 'id'),
                  'pay_period_id': ('pay_periods', 'id'),
                  'posted_entry_id': ('journal_entries', 'id')},
 'periods': {'bell_schedule_id': ('bell_schedules', 'id')},
 'person_addresses': {'address_id': ('addresses', 'id'),
                      'person_id': ('persons', 'id')},
 'person_contacts': {'contact_id': ('contacts', 'id'),
                     'person_id': ('persons', 'id')},
 'personal_notes': {'user_id': ('users', 'id')},
 'plan_alignments': {'agenda_item_id': ('agenda_items', 'id'),
                     'objective_id': ('objectives', 'id'),
                     'policy_id': ('policies', 'id')},
 'plan_filters': {'plan_id': ('plans', 'id')},
 'plan_search_index': {'plan_id': ('plans', 'id')},
 'plans': {'org_id': ('organizations', 'id')},
 'pm_plans': {'asset_id': ('assets', 'id'), 'building_id': ('buildings', 'id')},
 'pm_work_generators': {'pm_plan_id': ('pm_plans', 'id')},
 'policies': {'org_id': ('organizations', 'id')},
 'policy_approvals': {'approver_id': ('users', 'id'),
                      'policy_version_id': ('policy_versions', 'id'),
                      'step_id': ('policy_workflow_steps', 'id')},
 'policy_comments': {'policy_version_id': ('policy_versions', 'id'),
                     'user_id': ('users', 'id')},
 'policy_files': {'file_id': ('files', 'id'),
                  'policy_version_id': ('policy_versions', 'id')},
 'policy_legal_refs': {'policy_version_id': ('policy_versions', 'id')},
 'policy_publications': {'policy_version_id': ('policy_versions', 'id')},
 'policy_search_index': {'policy_id': ('policies', 'id')},
 'policy_versions': {'created_by': ('users', 'id'),
                     'policy_id': ('policies', 'id'),
                     'supersedes_version_id': ('policy_versions', 'id')},
 'policy_workflow_steps': {'workflow_id': ('policy_workflows', 'id')},
 'policy_workflows': {'policy_id': ('policies', 'id')},
 'post_attachments': {'file_id': ('files', 'id'), 'post_id': ('posts', 'id')},
 'posts': {'author_id': ('users', 'id'), 'channel_id': ('channels', 'id')},
 'project_tasks': {'assignee_user_id': ('users', 'id'),
                   'project_id': ('projects', 'id')},
 'projects': {'school_id': ('schools', 'id')},
 'proposal_documents': {'document_id': ('documents', 'id'),
                        'proposal_id': ('proposals', 'id')},
 'proposal_reviews': {'proposal_id': ('proposals', 'id'),
                      'review_round_id': ('review_rounds', 'id'),
                      'reviewer_id': ('persons', 'id')},
 'proposal_standard_map': {'proposal_id': ('proposals', 'id'),
                           'standard_id': ('standards', 'id')},
 'proposals': {'committee_id': ('committees', 'id'),
               'course_id': ('courses', 'id'),
               'organization_id': ('organizations', 'id'),
               'school_id': ('schools', 'id'),
               'subject_id': ('subjects', 'id'),
               'submitted_by_id': ('persons', 'id'),
               "association_id": ("associations", "id")},
 'publications': {'meeting_id': ('meetings', 'id')},
 'report_cards': {'student_id': ('students', 'id'),
                  'term_id': ('academic_terms', 'id')},
 'requirements': {'state_code': ('states', 'code')},
 'resolutions': {'meeting_id': ('meetings', 'id')},
 'review_requests': {'association_id': ('education_associations', 'id'),
                     'curriculum_version_id': ('curriculum_versions', 'id')},
 'review_rounds': {'proposal_id': ('proposals', 'id')},
 'reviews': {'review_round_id': ('review_rounds', 'id'),
             'reviewer_id': ('reviewers', 'id')},
 'role_permissions': {'permission_id': ('permissions', 'id'),
                      'role_id': ('roles', 'id')},
 'rooms': {'school_id': ('schools', 'id')},
 'round_decisions': {'review_round_id': ('review_rounds', 'id')},
 'scan_results': {'ticket_id': ('tickets', 'id')},
 'schools': {'organization_id': ('organizations', 'id')},
 'score_entries': {'game_id': ('games', 'id'), 'team_id': ('teams', 'id')},
 'scorecard_kpis': {'kpi_id': ('kpis', 'id'),
                    'scorecard_id': ('scorecards', 'id')},
 'scorecards': {'plan_id': ('plans', 'id')},
 'section504_plans': {'student_id': ('students', 'id')},
 'section_meetings': {'period_id': ('periods', 'id'),
                      'room_id': ('rooms', 'id'),
                      'section_id': ('course_sections', 'id')},
 'section_room_assignments': {'room_id': ('rooms', 'id'),
                              'section_id': ('course_sections', 'id')},
 'sessions': {'student_id': ('students', 'id')},
 'space_reservations': {'booked_by_user_id': ('users', 'id'),
                        'space_id': ('spaces', 'id')},
 'spaces': {'building_id': ('buildings', 'id'), 'floor_id': ('floors', 'id')},
 'special_education_cases': {'student_id': ('students', 'id')},
 'standards': {'framework_id': ('frameworks', 'id'),
               'parent_id': ('standards', 'id')},
 'store_order_items': {'order_id': ('store_orders', 'id'),
                       'product_id': ('store_products', 'id')},
 'student_guardians': {'guardian_id': ('guardians', 'id'),
                       'student_id': ('students', 'id')},
 'student_program_enrollments': {'student_id': ('students', 'id')},
 'student_school_enrollments': {'school_id': ('schools', 'id'),
                                'student_id': ('students', 'id')},
 'student_section_enrollments': {'section_id': ('course_sections', 'id'),
                                 'student_id': ('students', 'id')},
 'student_submissions': {'coursework_id': ('coursework', 'id'),
                         'student_user_id': ('users', 'id'),
                         'user_profile_id': ('user_profiles', 'id')},
 'student_transportation_assignments': {'route_id': ('bus_routes', 'id'),
                                        'stop_id': ('bus_stops', 'id'),
                                        'student_id': ('students', 'id')},
 'students': {'person_id': ('persons', 'id')},
 'subjects': {'department_id': ('departments', 'id')},
 'subscriptions': {'channel_id': ('channels', 'id')},
 'teacher_section_assignments': {'section_id': ('course_sections', 'id'),
                                 'staff_id': ('staff', 'id')},
 'team_messages': {'team_id': ('teams', 'id')},
 'teams': {'school_id': ('schools', 'id'),
           'season_id': ('seasons', 'id'),
           'sport_id': ('sports', 'id')},
 'test_administrations': {'school_id': ('schools', 'id'),
                          'test_id': ('standardized_tests', 'id')},
 'test_results': {'administration_id': ('test_administrations', 'id'),
                  'student_id': ('students', 'id')},
 'ticket_scans': {'scanned_by_user_id': ('users', 'id'),
                  'ticket_id': ('tickets', 'id')},
 'ticket_types': {'event_id': ('events', 'id')},
 'tickets': {'event_id': ('events', 'id'),
             'order_id': ('orders', 'id'),
             'ticket_type_id': ('ticket_types', 'id')},
 'topics': {'course_id': ('courses', 'id'), 'user_id': ('users', 'id')},
 'transcript_lines': {'course_id': ('courses', 'id'),
                      'student_id': ('students', 'id'),
                      'term_id': ('academic_terms', 'id')},
 'turn_in': {'session_id': ('sessions', 'id')},
 'tutor_out': {'tutor_id': ('tutors', 'id')},
 'tutor_spec': {'tutor_id': ('tutors', 'id')},
 'unit_standard_map': {'standard_id': ('standards', 'id'),
                       'unit_id': ('curriculum_units', 'id')},
 'user_accounts': {'person_id': ('persons', 'id')},
 'user_profiles': {'user_id': ('users', 'id')},
 'votes': {'motion_id': ('motions', 'id'), 'voter_id': ('users', 'id')},
 'waivers': {'student_id': ('students', 'id')},
 'warranties': {'asset_id': ('assets', 'id'), 'vendor_id': ('vendors', 'id')},
 'work_assignments': {'event_id': ('events', 'id'),
                      'worker_id': ('workers', 'id')},
 'work_order_parts': {'part_id': ('parts', 'id'),
                      'work_order_id': ('work_orders', 'id')},
 'work_order_tasks': {'work_order_id': ('work_orders', 'id')},
 'work_order_time_logs': {'user_id': ('users', 'id'),
                          'work_order_id': ('work_orders', 'id')},
 'work_orders': {'asset_id': ('assets', 'id'),
                 'assigned_to_user_id': ('users', 'id'),
                 'building_id': ('buildings', 'id'),
                 'request_id': ('maintenance_requests', 'id'),
                 'school_id': ('schools', 'id'),
                 'space_id': ('spaces', 'id')}}
