site_name: Open Source School Software
site_url: https://OSSS.code-specialist.com/
site_description: "Python Package: FastAPI Keycloak Integration"
site_author: Will Rubel
repo_url: https://github.com/rubelw/OSSS
repo_name: OSSS

theme:
  name: material
  locale: en
  highlightjs: true
  favicon: ./img/favicon.svg
  logo: ./img/logo.png
  hljs_languages:
    - yaml
    - python
    - bash
    - shell
  palette:
    - scheme: default
      primary: custom     # ← use CSS variables for header color
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: custom     # ← keep gray even in dark scheme
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Nunito Sans
    code: IBM Plex Mono

nav:
- Introduction: ./index.md
- Quickstart: ./quick_start.md
- Keycloak Configuration: ./keycloak_configuration.md
- Full example: ./full_example.md
- API Reference: ./reference.md
- Known issues: ./apple-m1.md

markdown_extensions:
- pymdownx.highlight
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.snippets
- toc:
    permalink:
- admonition
- attr_list
- def_list
- abbr
- markdown_include.include:
    base_path: docs/
- pymdownx.snippets

extra_css:
- ./css/styles.css

plugins:
- search
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
        setup_commands:
        - import sys
        - sys.path.append("OSSS")

