name: Build & Deploy Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read          # to checkout
  pages: write            # REQUIRED for deploy-pages
  id-token: write         # REQUIRED for OIDC (deploy-pages)

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node for TypeDoc (frontend API docs)
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Python for MkDocs
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps for docs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
         pip install "fastapi>=0.110" "pydantic>=2" "pydantic-settings>=2" "sqlalchemy>=2" "uvicorn"

          # Optional: if your mkdocs-gen-files script pulls backend imports, either:
          # pip install "fastapi>=0.110" "pydantic>=2" "pydantic-settings>=2" "sqlalchemy>=2" "uvicorn"
          # or skip it by setting DOCS_SKIP_OPENAPI=1 below.

      - name: Install frontend deps (for typedoc types)
        working-directory: src/osss-web
        run: |
          npm ci
          # If needed:
          # npm i -D @types/react @types/react-dom @types/node

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build TypeDoc (frontend)
        run: npx typedoc --options typedoc.frontend.json --skipErrorChecking --logLevel error

      - name: Build MkDocs
        env:
          DOCS_SKIP_OPENAPI: "1"   # set to 0/remove if you installed backend deps above
        run: mkdocs build --clean -f mkdocs.yaml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: documentation   # must match mkdocs 'site_dir'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
